;; SPDX-License-Identifier: PMPL-1.0-or-later
;; ECOSYSTEM.scm - stapeln's position in the verified container ecosystem

(ecosystem
 (version "1.0")
 (name "stapeln")
 (type "ui-tool")
 (purpose "Visual drag-and-drop designer for creating container stacks using verified containers")

 (position-in-ecosystem
  (role "developer-tool")
  (layer "ui-orchestration")
  (description "stapeln provides a graphical interface for designing multi-container stacks using Cerro Torre, Svalinn, selur, and Vörðr. It generates compose.toml files for selur-compose and validates stack configurations using formal verification."))

 (related-projects
  ((name . "selur-compose")
   (relationship . "sibling-standard")
   (description . "stapeln generates compose.toml files that selur-compose consumes for deployment"))
  ((name . "cerro-torre")
   (relationship . "sibling-standard")
   (description . "stapeln includes Cerro Torre as a draggable component for .ctp bundle creation"))
  ((name . "lago-grey")
   (relationship . "sibling-standard")
   (description . "stapeln includes Lago Grey as base image designer - Alpine/Chainguard alternative for minimal, secure base images"))
  ((name . "svalinn")
   (relationship . "sibling-standard")
   (description . "stapeln models Svalinn as an edge gateway component in the stack"))
  ((name . "selur")
   (relationship . "sibling-standard")
   (description . "stapeln represents selur as the IPC bridge layer between components"))
  ((name . "vordr")
   (relationship . "sibling-standard")
   (description . "stapeln models Vörðr as the container runtime/orchestrator"))
  ((name . "verified-container-spec")
   (relationship . "protocol-specification")
   (description . "stapeln validates generated stacks against verified-container-spec schemas"))
  ((name . "verisimdb")
   (relationship . "sibling-standard")
   (description . "stapeln uses VeriSimDB for stack metadata storage (6 modalities: graph, vector, tensor, semantic, document, temporal)"))
  ((name . "a2ml")
   (relationship . "sibling-standard")
   (description . "stapeln uses A2ML for attested component documentation with progressive strictness"))
  ((name . "k9-svc")
   (relationship . "sibling-standard")
   (description . "stapeln uses K9-SVC for self-validating component configurations"))
  ((name . "rescript-tea")
   (relationship . "inspiration")
   (description . "TEA architecture for predictable UI state management"))
  ((name . "cadre-tea-router")
   (relationship . "inspiration")
   (description . "Routing for ReScript-TEA applications"))
  ((name . "ephapax")
   (relationship . "sibling-standard")
   (description . "Backend uses Ephapax linear types for stack validation"))
  ((name . "affinescript")
   (relationship . "potential-consumer")
   (description . "Backend uses AffineScript for resource constraints"))
  ((name . "minikanren")
   (relationship . "external-dependency")
   (description . "stapeln uses miniKanren for deterministic security rule reasoning and attack surface analysis"))
  ((name . "owasp-modsecurity")
   (relationship . "external-integration")
   (description . "stapeln integrates OWASP ModSecurity Core Rule Set for firewall protection"))
  ((name . "rekor")
   (relationship . "external-integration")
   (description . "stapeln verifies container signatures via Rekor transparency log")))

 (provides
  (capability "visual-stack-design")
  (capability "drag-and-drop-ui")
  (capability "compose-file-generation")
  (capability "formal-stack-validation")
  (capability "attack-surface-analysis")
  (capability "security-gap-detection")
  (capability "ephemeral-firewall-pinholes")
  (capability "real-time-security-scoring")
  (capability "simulation-mode")
  (capability "wcag-2.3-aaa-accessibility")
  (interface "web-ui-http-api")
  (interface "graphql-api"))

 (consumes
  (dependency "rescript-tea")
  (dependency "cadre-tea-router")
  (dependency "deno-runtime")
  (dependency "phoenix-framework")
  (dependency "ephapax-linear")
  (dependency "idris2-proofs")
  (dependency "verisimdb")
  (dependency "a2ml")
  (dependency "k9-svc")
  (dependency "minikanren")
  (dependency "guile-scheme")
  (dependency "owasp-modsecurity-crs")
  (dependency "firewalld")
  (dependency "pam-authentication"))

 (integration-points
  ((component . "selur-compose")
   (method . "compose-toml-export")
   (description . "stapeln exports compose.toml files that selur-compose can deploy"))
  ((component . "cerro-torre")
   (method . "ct-cli-integration")
   (description . "stapeln can invoke ct commands for bundle creation"))
  ((component . "lago-grey")
   (method . "base-image-designer")
   (description . "stapeln integrates lago-grey for designing minimal, secure base images (Alpine/Chainguard alternative)"))
  ((component . "verisimdb")
   (method . "graphql-api")
   (description . "stapeln stores stack metadata in VeriSimDB using 6 modalities"))
  ((component . "a2ml")
   (method . "parser-integration")
   (description . "stapeln renders A2ML attested documentation for components"))
  ((component . "k9-svc")
   (method . "validator-integration")
   (description . "stapeln validates component configs using K9-SVC Nickel contracts"))
  ((component . "minikanren")
   (method . "scheme-ipc")
   (description . "stapeln queries miniKanren for security rule violations"))
  ((component . "modsecurity")
   (method . "svalinn-integration")
   (description . "stapeln configures OWASP ModSecurity CRS rules in Svalinn gateway"))
  ((component . "firewalld")
   (method . "cli-integration")
   (description . "stapeln manages firewall rules and ephemeral pinholes"))
  ((component . "rekor")
   (method . "api-client")
   (description . "stapeln verifies container signatures via Rekor transparency log"))
  ((component . "podman")
   (method . "api-client")
   (description . "stapeln can deploy directly to Podman via HTTP API"))
  ((component . "docker")
   (method . "api-client")
   (description . "stapeln can deploy directly to Docker via HTTP API"))
  ((component . "nerdctl")
   (method . "cli-wrapper")
   (description . "stapeln can deploy via nerdctl CLI")))

 (what-this-is
  "A visual drag-and-drop web application for designing container stacks with built-in attack surface analysis and security reasoning. Users experience a game-like interface (think spaceship customizer) where they drag components onto a canvas, see real-time security scoring, get automatic vulnerability detection, and receive actionable fix suggestions. Features three views: Paragon (vertical stack), Cisco (network topology), and Settings. Includes miniKanren-based security reasoning engine that queries OWASP/CVE rules for deterministic vulnerability detection. Implements WCAG 2.3 AAA accessibility (full ARIA, Braille, semantic XML). Uses VeriSimDB for multi-modal storage, A2ML for attested documentation, K9-SVC for self-validating configs. Backend is Elixir/Phoenix with GraphQL API, ephemeral firewall pinholes, and OWASP ModSecurity integration. Frontend is pure ReScript-TEA on Deno. Named 'stapeln' (Swedish for 'the stack') matching Nordic naming theme. Designed to convert container-haters: 'If you have to read the manual, we failed.'")

 (what-this-is-not
  "Not a container runtime (use Podman/Docker/nerdctl). Not a CLI tool (use selur-compose for CLI). Not a replacement for compose files (generates them). Not a general-purpose diagram tool (specific to verified containers). Not a monitoring dashboard (focused on design/configuration). Not a CI/CD system (generates configs for deployment). Not using an SLM for security (uses deterministic miniKanren instead). Not a penetration testing tool (does static analysis only). Not a vulnerability scanner replacement (integrates Grype for CVEs)."))
