// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DomMounterEnhanced from "./DomMounterEnhanced.res.js";

function isSSR() {
  return (typeof window === 'undefined');
}

function isClient() {
  return !isSSR();
}

function mountSSR(elementId) {
  if (isSSR()) {
    if (elementId.length === 0) {
      return {
        TAG: "Error",
        _0: "Element ID cannot be empty"
      };
    } else {
      console.log(`SSR: Marking ` + elementId + ` for client-side hydration`);
      return {
        TAG: "Ok",
        _0: undefined
      };
    }
  } else {
    return DomMounterEnhanced.mount(elementId);
  }
}

function mountWithHydration(elementId) {
  if (isSSR()) {
    return mountSSR(elementId);
  }
  let hasSSRMarker = ((id) => {
        const element = document.getElementById(id);
        return element && element.hasAttribute('data-ssr-rendered');
      });
  if (hasSSRMarker(elementId)) {
    console.log(`Hydrating ` + elementId);
    ((document.getElementById(elementId).removeAttribute('data-ssr-rendered')));
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return DomMounterEnhanced.mount(elementId);
  }
}

export {
  isSSR,
  isClient,
  mountSSR,
  mountWithHydration,
}
/* No side effect */
