// Generated by ReScript, PLEASE EDIT WITH CARE


let WebComponentsFFI = {};

function registerMountedComponent(tagName) {
  let customElement = (class MountedComponent extends HTMLElement {
      connectedCallback() {
        const elementId = this.getAttribute('element-id');
        if (elementId) {
          // Mount using DomMounterEnhanced
          this._mountResult = mount(elementId);

          // Add indicator attribute
          if (this._mountResult.tag === 'Ok') {
            this.setAttribute('data-mounted', 'true');
          } else {
            this.setAttribute('data-mount-error', this._mountResult.error);
          }
        }
      }

      disconnectedCallback() {
        const elementId = this.getAttribute('element-id');
        if (elementId) {
          // Unmount (would call unmount function)
          this.removeAttribute('data-mounted');
        }
      }
    });
  customElements.define(tagName, customElement);
}

export {
  WebComponentsFFI,
  registerMountedComponent,
}
/* No side effect */
