// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as React from "react";
import * as Update from "./Update.res.js";
import * as StackView from "./StackView.res.js";
import * as IdrisBadge from "./IdrisBadge.res.js";
import * as GapAnalysis from "./GapAnalysis.res.js";
import * as TopologyView from "./TopologyView.res.js";
import * as ErrorBoundary from "./ErrorBoundary.res.js";
import * as SimulationMode from "./SimulationMode.res.js";
import * as PortConfigPanel from "./PortConfigPanel.res.js";
import * as SecurityInspector from "./SecurityInspector.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as LagoGreyImageDesigner from "./LagoGreyImageDesigner.res.js";

let initialAppState = {
  currentPage: "NetworkView",
  model: Model.initialModel,
  isDark: true
};

function App(props) {
  let match = React.useState(() => initialAppState);
  let setState = match[1];
  let state = match[0];
  let dispatch = msg => {
    let newModel = Update.update(state.model, msg);
    setState(prev => ({
      currentPage: prev.currentPage,
      model: newModel,
      isDark: prev.isDark
    }));
  };
  let switchPage = page => setState(prev => ({
    currentPage: page,
    model: prev.model,
    isDark: prev.isDark
  }));
  let match$1 = state.currentPage;
  let tmp;
  switch (match$1) {
    case "NetworkView" :
      tmp = TopologyView.view(state.model, state.isDark, dispatch);
      break;
    case "StackView" :
      tmp = StackView.view(state.model);
      break;
    case "LagoGreyView" :
      tmp = JsxRuntime.jsx(LagoGreyImageDesigner.make, {});
      break;
    case "PortConfigView" :
      tmp = JsxRuntime.jsx(PortConfigPanel.make, {});
      break;
    case "SecurityView" :
      tmp = JsxRuntime.jsx(SecurityInspector.make, {});
      break;
    case "GapAnalysisView" :
      tmp = JsxRuntime.jsx(GapAnalysis.make, {});
      break;
    case "SimulationView" :
      tmp = JsxRuntime.jsx(SimulationMode.make, {});
      break;
    case "SettingsView" :
      tmp = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "Settings"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Theme"
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    checked: state.isDark,
                    type: "checkbox",
                    onChange: param => setState(prev => ({
                      currentPage: prev.currentPage,
                      model: prev.model,
                      isDark: !prev.isDark
                    }))
                  }),
                  " Dark Mode"
                ]
              })
            ],
            className: "settings-group"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Default Runtime"
              }),
              JsxRuntime.jsx("p", {
                children: "Podman / Docker / nerdctl selection coming soon"
              })
            ],
            className: "settings-group"
          })
        ],
        className: "page settings-page"
      });
      break;
  }
  return JsxRuntime.jsx(ErrorBoundary.make, {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsxs("nav", {
          children: [
            JsxRuntime.jsx("button", {
              children: "🌐 Network",
              className: state.currentPage === "NetworkView" ? "tab active" : "tab",
              onClick: param => switchPage("NetworkView")
            }),
            JsxRuntime.jsx("button", {
              children: "📚 Stack",
              className: state.currentPage === "StackView" ? "tab active" : "tab",
              onClick: param => switchPage("StackView")
            }),
            JsxRuntime.jsx("button", {
              children: "🏔️ Lago Grey",
              className: state.currentPage === "LagoGreyView" ? "tab active" : "tab",
              onClick: param => switchPage("LagoGreyView")
            }),
            JsxRuntime.jsx("button", {
              children: "🔌 Ports",
              className: state.currentPage === "PortConfigView" ? "tab active" : "tab",
              onClick: param => switchPage("PortConfigView")
            }),
            JsxRuntime.jsx("button", {
              children: "🛡️ Security",
              className: state.currentPage === "SecurityView" ? "tab active" : "tab",
              onClick: param => switchPage("SecurityView")
            }),
            JsxRuntime.jsx("button", {
              children: "🔍 Gaps",
              className: state.currentPage === "GapAnalysisView" ? "tab active" : "tab",
              onClick: param => switchPage("GapAnalysisView")
            }),
            JsxRuntime.jsx("button", {
              children: "🎮 Simulation",
              className: state.currentPage === "SimulationView" ? "tab active" : "tab",
              onClick: param => switchPage("SimulationView")
            }),
            JsxRuntime.jsx("button", {
              children: "⚙️ Settings",
              className: state.currentPage === "SettingsView" ? "tab active" : "tab",
              onClick: param => switchPage("SettingsView")
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                  children: "📂 Import",
                  className: "action-btn",
                  title: "Import design from JSON file",
                  onClick: param => dispatch("TriggerImportDesign")
                }),
                JsxRuntime.jsx("button", {
                  children: "💾 Export",
                  className: "action-btn",
                  title: "Export design to JSON file",
                  onClick: param => dispatch({
                    TAG: "ExportDesignToJson",
                    _0: "Stack design"
                  })
                })
              ],
              className: "nav-actions"
            })
          ],
          className: "nav-tabs"
        }),
        JsxRuntime.jsx("div", {
          children: tmp,
          className: "content"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx(IdrisBadge.make, {
            style: "Compact"
          }),
          style: {
            bottom: "16px",
            position: "fixed",
            right: "16px",
            zIndex: "1000"
          }
        })
      ],
      className: "app"
    })
  });
}

let make = App;

export {
  initialAppState,
  make,
}
/* react Not a pure module */
