// Generated by ReScript, PLEASE EDIT WITH CARE


function resultFromInt(code) {
  switch (code) {
    case 0 :
      return "Success";
    case 1 :
      return "ElementNotFound";
    case 3 :
      return "AlreadyMounted";
    default:
      return "InvalidId";
  }
}

let FFI = {
  resultFromInt: resultFromInt
};

function mount(elementId) {
  if (elementId.length === 0) {
    return {
      TAG: "Error",
      _0: "Element ID cannot be empty"
    };
  }
  if (!check_element_exists(elementId)) {
    return {
      TAG: "Error",
      _0: "Element does not exist in DOM: " + elementId
    };
  }
  let code = mount_to_element(elementId);
  let match = resultFromInt(code);
  switch (match) {
    case "Success" :
      return {
        TAG: "Ok",
        _0: undefined
      };
    case "ElementNotFound" :
      return {
        TAG: "Error",
        _0: "Element not found: " + elementId
      };
    case "InvalidId" :
      return {
        TAG: "Error",
        _0: "Invalid element ID: " + elementId
      };
    case "AlreadyMounted" :
      return {
        TAG: "Error",
        _0: "Element already mounted: " + elementId
      };
  }
}

function mountToApp() {
  return mount("app");
}

function mountWithCallback(elementId, onSuccess, onError) {
  let msg = mount(elementId);
  if (msg.TAG === "Ok") {
    return onSuccess();
  } else {
    return onError(msg._0);
  }
}

function mountReactApp(elementId) {
  let msg = mount(elementId);
  if (msg.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: msg._0
    };
  }
  console.log("DOM element validated with Idris2 proofs");
  return {
    TAG: "Ok",
    _0: undefined
  };
}

export {
  FFI,
  mount,
  mountToApp,
  mountWithCallback,
  mountReactApp,
}
/* No side effect */
