// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HealthIndicator(props) {
  let health = props.health;
  let match = health >= 90 ? [
      "#4caf50",
      "Excellent"
    ] : (
      health >= 75 ? [
          "#4a9eff",
          "Good"
        ] : (
          health >= 50 ? [
              "#ff9800",
              "Fair"
            ] : (
              health >= 25 ? [
                  "#f44336",
                  "Poor"
                ] : [
                  "#d32f2f",
                  "Critical"
                ]
            )
        )
    );
  let color = match[0];
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: " ❤️",
        style: {
          fontSize: "20px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "System Health",
            style: {
              color: "#8892a6",
              fontSize: "12px",
              marginBottom: "2px"
            }
          }),
          JsxRuntime.jsx("div", {
            children: String(health) + "% - " + match[1],
            style: {
              color: color,
              fontSize: "18px",
              fontWeight: "700"
            }
          })
        ]
      })
    ],
    style: {
      background: "rgba(30, 36, 49, 0.8)",
      border: "2px solid " + color,
      display: "flex",
      padding: "12px 20px",
      borderRadius: "8px",
      alignItems: "center",
      gap: "12px"
    }
  });
}

let make = HealthIndicator;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
