// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

let root = document.querySelector("#app");

if (root == null) {
  console.error("Root element #app not found");
} else {
  let reactRoot = Client.createRoot(root);
  reactRoot.render(JsxRuntime.jsx(App.make, {}));
}

/* root Not a pure module */
