// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "@rescript/runtime/lib/es6/Js_math.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

let initialModel_components = [];

let initialModel_connections = [];

let initialModel_canvasOffset = {
  x: 0.0,
  y: 0.0
};

let initialModel = {
  components: initialModel_components,
  connections: initialModel_connections,
  selectedComponent: undefined,
  dragState: "NotDragging",
  canvasOffset: initialModel_canvasOffset,
  zoomLevel: 1.0,
  validationResult: undefined
};

function generateId() {
  let uuid = "";
  for (let i = 0; i <= 35; ++i) {
    let idx = Js_math.random_int(0, 16);
    let char = "0123456789abcdef".charAt(idx);
    uuid = uuid + char;
    if (i === 7 || i === 12 || i === 17 || i === 22) {
      uuid = uuid + "-";
    }
  }
  return uuid;
}

function findComponent(model, id) {
  return Belt_Array.getBy(model.components, c => c.id === id);
}

function componentTypeToString(ct) {
  switch (ct) {
    case "CerroTorre" :
      return "Cerro Torre";
    case "LagoGrey" :
      return "Lago Grey";
    case "Svalinn" :
      return "Svalinn";
    case "Selur" :
      return "selur";
    case "Vordr" :
      return "Vörðr";
    case "Podman" :
      return "Podman";
    case "Docker" :
      return "Docker";
    case "Nerdctl" :
      return "nerdctl";
    case "Volume" :
      return "Volume";
    case "Network" :
      return "Network";
  }
}

export {
  initialModel,
  generateId,
  findComponent,
  componentTypeToString,
}
/* No side effect */
