// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

let init_ports = [
  {
    number: 22,
    protocol: "SSH",
    state: "Closed",
    risk: "Critical",
    description: "Secure Shell"
  },
  {
    number: 80,
    protocol: "HTTP",
    state: "Closed",
    risk: "Medium",
    description: "Web Server"
  },
  {
    number: 443,
    protocol: "HTTPS",
    state: "Closed",
    risk: "Medium",
    description: "Secure Web"
  },
  {
    number: 3306,
    protocol: "MySQL",
    state: "Closed",
    risk: "High",
    description: "MySQL Database"
  },
  {
    number: 5432,
    protocol: "PostgreSQL",
    state: "Closed",
    risk: "High",
    description: "PostgreSQL DB"
  },
  {
    number: 8080,
    protocol: "HTTP-Alt",
    state: "Closed",
    risk: "Safe",
    description: "Alt HTTP"
  },
  {
    number: 9000,
    protocol: "Custom",
    state: "Closed",
    risk: "Safe",
    description: "Application"
  }
];

let init = {
  ports: init_ports,
  selectedPort: undefined,
  showEphemeralConfig: false,
  ephemeralDuration: 300,
  ephemeralRemaining: undefined
};

function update(msg, state) {
  if (typeof msg !== "object") {
    return {
      ports: state.ports,
      selectedPort: state.selectedPort,
      showEphemeralConfig: !state.showEphemeralConfig,
      ephemeralDuration: state.ephemeralDuration,
      ephemeralRemaining: state.ephemeralRemaining
    };
  }
  switch (msg.TAG) {
    case "SelectPort" :
      return {
        ports: state.ports,
        selectedPort: msg._0,
        showEphemeralConfig: state.showEphemeralConfig,
        ephemeralDuration: state.ephemeralDuration,
        ephemeralRemaining: state.ephemeralRemaining
      };
    case "SetPortState" :
      let newState = msg._1;
      let portNum = msg._0;
      let updatedPorts = Belt_Array.map(state.ports, port => {
        if (port.number === portNum) {
          return {
            number: port.number,
            protocol: port.protocol,
            state: newState,
            risk: port.risk,
            description: port.description
          };
        } else {
          return port;
        }
      });
      return {
        ports: updatedPorts,
        selectedPort: state.selectedPort,
        showEphemeralConfig: state.showEphemeralConfig,
        ephemeralDuration: state.ephemeralDuration,
        ephemeralRemaining: state.ephemeralRemaining
      };
    case "SetEphemeralDuration" :
      return {
        ports: state.ports,
        selectedPort: state.selectedPort,
        showEphemeralConfig: state.showEphemeralConfig,
        ephemeralDuration: msg._0,
        ephemeralRemaining: state.ephemeralRemaining
      };
    case "StartEphemeralTimer" :
      return {
        ports: state.ports,
        selectedPort: state.selectedPort,
        showEphemeralConfig: state.showEphemeralConfig,
        ephemeralDuration: state.ephemeralDuration,
        ephemeralRemaining: state.ephemeralDuration
      };
    case "DecrementEphemeralTimer" :
      let remaining = state.ephemeralRemaining;
      if (remaining !== undefined && remaining > 0) {
        return {
          ports: state.ports,
          selectedPort: state.selectedPort,
          showEphemeralConfig: state.showEphemeralConfig,
          ephemeralDuration: state.ephemeralDuration,
          ephemeralRemaining: remaining - 1 | 0
        };
      } else {
        return state;
      }
    case "ExpireEphemeralPort" :
      let portNum$1 = msg._0;
      let updatedPorts$1 = Belt_Array.map(state.ports, port => {
        if (port.number === portNum$1) {
          return {
            number: port.number,
            protocol: port.protocol,
            state: "Closed",
            risk: port.risk,
            description: port.description
          };
        } else {
          return port;
        }
      });
      return {
        ports: updatedPorts$1,
        selectedPort: state.selectedPort,
        showEphemeralConfig: state.showEphemeralConfig,
        ephemeralDuration: state.ephemeralDuration,
        ephemeralRemaining: undefined
      };
  }
}

function riskIndicator(risk) {
  switch (risk) {
    case "Critical" :
      return "🔴";
    case "High" :
      return "🟠";
    case "Medium" :
      return "🟡";
    case "Safe" :
      return "✅";
  }
}

function riskColor(risk) {
  switch (risk) {
    case "Critical" :
      return "#f44336";
    case "High" :
      return "#ff9800";
    case "Medium" :
      return "#ffc107";
    case "Safe" :
      return "#4caf50";
  }
}

function formatDuration(seconds) {
  if (seconds < 60) {
    return String(seconds) + "s";
  } else if (seconds < 3600) {
    return String(seconds / 60 | 0) + "m";
  } else if (seconds < 86400) {
    return String(seconds / 3600 | 0) + "h";
  } else {
    return String(seconds / 86400 | 0) + "d";
  }
}

function stateLabel(state) {
  if (typeof state !== "object") {
    if (state === "Closed") {
      return "Closed";
    } else {
      return "Open";
    }
  } else {
    return "Ephemeral (" + formatDuration(state._0) + ")";
  }
}

function stateColor(state) {
  if (typeof state !== "object") {
    if (state === "Closed") {
      return "#4caf50";
    } else {
      return "#f44336";
    }
  } else {
    return "#ff9800";
  }
}

function viewPortRow(port, dispatch) {
  let match = port.state;
  let tmp;
  tmp = typeof match !== "object" ? "#2a3142" : "#ff9800";
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: riskIndicator(port.risk),
            style: {
              fontSize: "24px"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Port " + String(port.number),
                style: {
                  color: "#e0e6ed",
                  fontSize: "16px",
                  fontWeight: "700"
                }
              }),
              JsxRuntime.jsx("div", {
                children: port.protocol + " - " + port.description,
                style: {
                  color: "#8892a6",
                  fontSize: "12px",
                  marginTop: "2px"
                }
              })
            ]
          })
        ],
        style: {
          display: "flex",
          alignItems: "center",
          gap: "16px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Closed",
            style: {
              background: port.state === "Closed" ? "#4caf50" : "#2a3142",
              border: "none",
              color: "white",
              cursor: "pointer",
              fontSize: "12px",
              fontWeight: "600",
              padding: "8px 16px",
              borderRadius: "6px"
            },
            onClick: param => dispatch({
              TAG: "SetPortState",
              _0: port.number,
              _1: "Closed"
            })
          }),
          JsxRuntime.jsx("button", {
            children: "Ephemeral",
            style: {
              background: tmp,
              border: "none",
              color: "white",
              cursor: "pointer",
              fontSize: "12px",
              fontWeight: "600",
              padding: "8px 16px",
              borderRadius: "6px"
            },
            onClick: param => dispatch({
              TAG: "SetPortState",
              _0: port.number,
              _1: {
                TAG: "Ephemeral",
                _0: 300
              }
            })
          }),
          JsxRuntime.jsx("button", {
            children: "Open",
            style: {
              background: port.state === "Open" ? "#f44336" : "#2a3142",
              border: "none",
              color: "white",
              cursor: "pointer",
              fontSize: "12px",
              fontWeight: "600",
              padding: "8px 16px",
              borderRadius: "6px"
            },
            onClick: param => dispatch({
              TAG: "SetPortState",
              _0: port.number,
              _1: "Open"
            })
          })
        ],
        style: {
          display: "flex",
          gap: "8px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: stateLabel(port.state),
        style: {
          background: stateColor(port.state),
          color: "white",
          fontSize: "11px",
          fontWeight: "700",
          minWidth: "80px",
          padding: "6px 12px",
          textAlign: "center",
          borderRadius: "6px"
        }
      })
    ],
    className: "port-row",
    style: {
      background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: "1px solid #2a3142",
      cursor: "pointer",
      display: "flex",
      marginBottom: "8px",
      padding: "16px",
      borderRadius: "12px",
      alignItems: "center",
      justifyContent: "space-between",
      transition: "all 0.2s"
    }
  }, String(port.number));
}

function viewEphemeralConfig(state, dispatch) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h3", {
        children: "⏱️ Ephemeral Pinhole Configuration",
        style: {
          color: "#ff9800",
          fontSize: "18px",
          fontWeight: "700",
          marginBottom: "16px"
        }
      }),
      JsxRuntime.jsx("p", {
        children: "Ephemeral pinholes automatically close after a set duration. Perfect for temporary access (SSH debugging, database migrations, etc.).",
        style: {
          color: "#b0b8c4",
          fontSize: "13px",
          lineHeight: "1.6",
          marginBottom: "16px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("label", {
            children: "Duration:",
            style: {
              color: "#8892a6",
              display: "block",
              fontSize: "12px",
              marginBottom: "8px"
            }
          }),
          JsxRuntime.jsx("div", {
            children: Belt_Array.map([
              30,
              60,
              300,
              600,
              1800,
              3600,
              7200,
              14400,
              43200,
              86400
            ], seconds => JsxRuntime.jsx("button", {
              children: formatDuration(seconds),
              style: {
                background: state.ephemeralDuration === seconds ? "#4a9eff" : "#2a3142",
                border: "none",
                color: "white",
                cursor: "pointer",
                fontSize: "12px",
                fontWeight: "600",
                padding: "8px 16px",
                borderRadius: "6px"
              },
              onClick: param => dispatch({
                TAG: "SetEphemeralDuration",
                _0: seconds
              })
            }, String(seconds))),
            style: {
              display: "flex",
              flexWrap: "wrap",
              gap: "8px"
            }
          })
        ],
        style: {
          marginBottom: "16px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("strong", {
            children: "Security Note:"
          }),
          " Ephemeral ports automatically close after the timer expires. All access is logged to VeriSimDB for audit."
        ],
        style: {
          background: "rgba(255, 152, 0, 0.1)",
          border: "1px solid #ff9800",
          color: "#ff9800",
          fontSize: "12px",
          padding: "12px",
          borderRadius: "6px"
        }
      })
    ],
    className: "ephemeral-config",
    style: {
      background: "#1e2431",
      border: "2px solid #ff9800",
      marginTop: "16px",
      padding: "24px",
      borderRadius: "12px"
    }
  });
}

function PortConfigPanel(props) {
  let onStateChange = props.onStateChange;
  let initialState = props.initialState;
  let match = React.useState(() => {
    if (initialState !== undefined) {
      return initialState;
    } else {
      return init;
    }
  });
  let setState = match[1];
  let state = match[0];
  let dispatch = msg => {
    let newState = update(msg, state);
    setState(param => newState);
    if (onStateChange !== undefined) {
      return onStateChange(newState);
    }
  };
  React.useEffect(() => {
    let remaining = state.ephemeralRemaining;
    if (remaining === undefined) {
      return;
    }
    if (remaining <= 0) {
      if (remaining !== 0) {
        return;
      } else {
        Belt_Array.forEach(state.ports, port => {
          let match = port.state;
          if (typeof match !== "object") {
            return;
          } else {
            return dispatch({
              TAG: "ExpireEphemeralPort",
              _0: port.number
            });
          }
        });
        return;
      }
    }
    let timeoutId = setTimeout(() => dispatch({
      TAG: "DecrementEphemeralTimer",
      _0: 0
    }), 1000);
    return () => {
      clearTimeout(timeoutId);
    };
  }, [state.ephemeralRemaining]);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "🔌 Port Configuration",
            style: {
              background: "linear-gradient(135deg, #4a9eff, #7b6cff)",
              fontSize: "32px",
              fontWeight: "700",
              marginBottom: "8px"
            }
          }),
          JsxRuntime.jsx("p", {
            children: "Configure which ports are accessible and for how long",
            style: {
              color: "#8892a6",
              fontSize: "16px"
            }
          })
        ],
        style: {
          marginBottom: "32px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map([
          [
            "Closed",
            Belt_Array.reduce(state.ports, 0, (acc, p) => {
              if (p.state === "Closed") {
                return acc + 1 | 0;
              } else {
                return acc;
              }
            }),
            "#4caf50"
          ],
          [
            "Open",
            Belt_Array.reduce(state.ports, 0, (acc, p) => {
              if (p.state === "Open") {
                return acc + 1 | 0;
              } else {
                return acc;
              }
            }),
            "#f44336"
          ],
          [
            "Ephemeral",
            Belt_Array.reduce(state.ports, 0, (acc, p) => {
              let match = p.state;
              if (typeof match !== "object") {
                return acc;
              } else {
                return acc + 1 | 0;
              }
            }),
            "#ff9800"
          ],
          [
            "Critical Risk",
            Belt_Array.reduce(state.ports, 0, (acc, p) => {
              if (p.risk === "Critical" && p.state !== "Closed") {
                return acc + 1 | 0;
              } else {
                return acc;
              }
            }),
            "#f44336"
          ]
        ], param => {
          let label = param[0];
          return JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: String(param[1]),
                style: {
                  color: param[2],
                  fontSize: "36px",
                  fontWeight: "700",
                  marginBottom: "8px"
                }
              }),
              JsxRuntime.jsx("div", {
                children: label,
                style: {
                  color: "#8892a6",
                  fontSize: "13px"
                }
              })
            ],
            style: {
              background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
              border: "2px solid #2a3142",
              padding: "20px",
              textAlign: "center",
              borderRadius: "12px"
            }
          }, label);
        }),
        style: {
          display: "grid",
          marginBottom: "32px",
          gap: "16px",
          gridTemplateColumns: "repeat(4, 1fr)"
        }
      }),
      JsxRuntime.jsx("button", {
        children: (
          state.showEphemeralConfig ? "Hide" : "Configure"
        ) + " Ephemeral Settings",
        style: {
          background: "linear-gradient(135deg, #ff9800, #f57c00)",
          border: "none",
          color: "white",
          cursor: "pointer",
          fontSize: "14px",
          fontWeight: "600",
          marginBottom: "16px",
          padding: "12px 24px",
          borderRadius: "8px"
        },
        onClick: param => dispatch("ToggleEphemeralConfig")
      }),
      state.showEphemeralConfig ? viewEphemeralConfig(state, dispatch) : null,
      JsxRuntime.jsx("div", {
        children: Belt_Array.map(state.ports, port => viewPortRow(port, dispatch)),
        style: {
          marginTop: "24px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h4", {
            children: "⚠️ Security Best Practices",
            style: {
              color: "#f44336",
              fontSize: "16px",
              fontWeight: "700",
              marginBottom: "12px"
            }
          }),
          JsxRuntime.jsxs("ul", {
            children: [
              JsxRuntime.jsx("li", {
                children: "Never leave SSH (22), RDP (3389), or database ports open permanently"
              }),
              JsxRuntime.jsx("li", {
                children: "Use ephemeral pinholes for temporary access - they auto-close"
              }),
              JsxRuntime.jsx("li", {
                children: "All port access is logged to VeriSimDB for compliance auditing"
              }),
              JsxRuntime.jsx("li", {
                children: "Default-deny firewall rules protect all closed ports"
              }),
              JsxRuntime.jsx("li", {
                children: "Critical risk ports trigger miniKanren security warnings"
              })
            ],
            style: {
              color: "#b0b8c4",
              fontSize: "13px",
              lineHeight: "1.8",
              paddingLeft: "20px"
            }
          })
        ],
        style: {
          background: "rgba(244, 67, 54, 0.1)",
          border: "2px solid #f44336",
          marginTop: "32px",
          padding: "20px",
          borderRadius: "12px"
        }
      })
    ],
    className: "port-config-panel",
    style: {
      background: "#0a0e1a",
      minHeight: "100vh",
      padding: "32px"
    }
  });
}

let make = PortConfigPanel;

export {
  init,
  update,
  riskIndicator,
  riskColor,
  formatDuration,
  stateLabel,
  stateColor,
  viewPortRow,
  viewEphemeralConfig,
  make,
}
/* react Not a pure module */
