// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function view(settings, isDark) {
  return JsxRuntime.jsxs("main", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Settings",
        style: {
          fontSize: "2rem",
          fontWeight: "700",
          marginBottom: "2rem"
        }
      }),
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Default Component Settings",
            id: "defaults-title",
            style: {
              fontSize: "1.5rem",
              fontWeight: "600",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsxs("fieldset", {
            children: [
              JsxRuntime.jsx("legend", {
                children: "Default Container Runtime",
                style: {
                  fontWeight: "600",
                  marginBottom: "0.5rem"
                }
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    defaultChecked: settings.defaultRuntime === "Podman",
                    name: "runtime",
                    type: "radio",
                    value: "podman"
                  }),
                  " Podman"
                ],
                style: {
                  display: "inline-block",
                  marginRight: "1rem"
                }
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    defaultChecked: settings.defaultRuntime === "Docker",
                    name: "runtime",
                    type: "radio",
                    value: "docker"
                  }),
                  " Docker"
                ],
                style: {
                  display: "inline-block",
                  marginRight: "1rem"
                }
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    defaultChecked: settings.defaultRuntime === "Nerdctl",
                    name: "runtime",
                    type: "radio",
                    value: "nerdctl"
                  }),
                  " nerdctl"
                ],
                style: {
                  display: "inline-block"
                }
              })
            ],
            style: {
              border: "none",
              marginBottom: "1rem",
              padding: "0"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("span", {
                children: "Default Registry",
                style: {
                  display: "block",
                  fontWeight: "600",
                  marginBottom: "0.5rem"
                }
              }),
              JsxRuntime.jsx("input", {
                "aria-label": "Default container registry",
                defaultValue: settings.defaultRegistry,
                style: {
                  backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                  border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                  borderRadius: "4px",
                  color: isDark ? "#FFFFFF" : "#000000",
                  maxWidth: "500px",
                  padding: "0.75rem",
                  width: "100%"
                },
                type: "text"
              })
            ],
            style: {
              display: "block",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("input", {
                "aria-label": "Automatically verify container signatures",
                defaultChecked: settings.autoVerifySignatures,
                type: "checkbox"
              }),
              " Auto-verify signatures"
            ],
            style: {
              display: "block",
              marginBottom: "0.5rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("input", {
                "aria-label": "Require SBOM for all containers",
                defaultChecked: settings.requireSBOM,
                type: "checkbox"
              }),
              " Require SBOM"
            ],
            style: {
              display: "block",
              marginBottom: "0.5rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("input", {
                "aria-label": "Enforce network policies",
                defaultChecked: settings.enforceNetworkPolicies,
                type: "checkbox"
              }),
              " Enforce network policies"
            ],
            style: {
              display: "block",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsx("h3", {
            children: "Default Resource Limits",
            style: {
              fontSize: "1.2rem",
              fontWeight: "600",
              margin: "1.5rem 0 1rem"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "CPU (cores)",
                    style: {
                      display: "block",
                      fontWeight: "600",
                      marginBottom: "0.5rem"
                    }
                  }),
                  JsxRuntime.jsx("input", {
                    "aria-label": "Default CPU limit in cores",
                    defaultValue: String(settings.defaultCpuLimit),
                    style: {
                      backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                      border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                      color: isDark ? "#FFFFFF" : "#000000",
                      padding: "0.75rem",
                      width: "100%",
                      borderRadius: "4px"
                    },
                    min: "0.1",
                    step: 0.1,
                    type: "number"
                  })
                ]
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "Memory (MB)",
                    style: {
                      display: "block",
                      fontWeight: "600",
                      marginBottom: "0.5rem"
                    }
                  }),
                  JsxRuntime.jsx("input", {
                    "aria-label": "Default memory limit in megabytes",
                    defaultValue: String(settings.defaultMemoryLimit),
                    style: {
                      backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                      border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                      color: isDark ? "#FFFFFF" : "#000000",
                      padding: "0.75rem",
                      width: "100%",
                      borderRadius: "4px"
                    },
                    min: "128",
                    step: 128.0,
                    type: "number"
                  })
                ]
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("span", {
                    children: "Storage (GB)",
                    style: {
                      display: "block",
                      fontWeight: "600",
                      marginBottom: "0.5rem"
                    }
                  }),
                  JsxRuntime.jsx("input", {
                    "aria-label": "Default storage limit in gigabytes",
                    defaultValue: String(settings.defaultStorageLimit),
                    style: {
                      backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                      border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                      color: isDark ? "#FFFFFF" : "#000000",
                      padding: "0.75rem",
                      width: "100%",
                      borderRadius: "4px"
                    },
                    min: "1",
                    step: 1.0,
                    type: "number"
                  })
                ]
              })
            ],
            style: {
              display: "grid",
              maxWidth: "600px",
              gap: "1rem",
              gridTemplateColumns: "repeat(3, 1fr)"
            }
          })
        ],
        "aria-labelledby": "defaults-title",
        role: "region",
        style: {
          border: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
          marginBottom: "2rem",
          padding: "1.5rem",
          borderRadius: "8px"
        }
      }),
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "🏔️ Cerro Torre Integration",
            id: "cerro-torre-title",
            style: {
              fontSize: "1.5rem",
              fontWeight: "600",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("span", {
                children: "CLI Path",
                style: {
                  display: "block",
                  fontWeight: "600",
                  marginBottom: "0.5rem"
                }
              }),
              JsxRuntime.jsx("input", {
                "aria-label": "Path to Cerro Torre CLI",
                defaultValue: settings.ctCliPath,
                style: {
                  backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                  border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                  color: isDark ? "#FFFFFF" : "#000000",
                  fontFamily: "monospace",
                  maxWidth: "500px",
                  padding: "0.75rem",
                  width: "100%",
                  borderRadius: "4px"
                },
                type: "text"
              })
            ],
            style: {
              display: "block",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("span", {
                children: "Default Signing Key",
                style: {
                  display: "block",
                  fontWeight: "600",
                  marginBottom: "0.5rem"
                }
              }),
              JsxRuntime.jsx("input", {
                "aria-label": "Path to default signing key",
                defaultValue: settings.ctSigningKey,
                style: {
                  backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                  border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                  color: isDark ? "#FFFFFF" : "#000000",
                  fontFamily: "monospace",
                  maxWidth: "500px",
                  padding: "0.75rem",
                  width: "100%",
                  borderRadius: "4px"
                },
                type: "text"
              })
            ],
            style: {
              display: "block",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("span", {
                children: "Transparency Log",
                style: {
                  display: "block",
                  fontWeight: "600",
                  marginBottom: "0.5rem"
                }
              }),
              JsxRuntime.jsx("input", {
                "aria-label": "Transparency log URL",
                defaultValue: settings.ctTransparencyLog,
                style: {
                  backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                  border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                  color: isDark ? "#FFFFFF" : "#000000",
                  maxWidth: "500px",
                  padding: "0.75rem",
                  width: "100%",
                  borderRadius: "4px"
                },
                type: "url"
              })
            ],
            style: {
              display: "block",
              marginBottom: "1rem"
            }
          })
        ],
        "aria-labelledby": "cerro-torre-title",
        role: "region",
        style: {
          border: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
          marginBottom: "2rem",
          padding: "1.5rem",
          borderRadius: "8px"
        }
      }),
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "UI Preferences",
            id: "ui-title",
            style: {
              fontSize: "1.5rem",
              fontWeight: "600",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsxs("fieldset", {
            children: [
              JsxRuntime.jsx("legend", {
                children: "Theme",
                style: {
                  fontWeight: "600",
                  marginBottom: "0.5rem"
                }
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    defaultChecked: settings.theme === "system",
                    name: "theme",
                    type: "radio",
                    value: "system"
                  }),
                  " System"
                ],
                style: {
                  display: "inline-block",
                  marginRight: "1rem"
                }
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    defaultChecked: settings.theme === "light",
                    name: "theme",
                    type: "radio",
                    value: "light"
                  }),
                  " Light"
                ],
                style: {
                  display: "inline-block",
                  marginRight: "1rem"
                }
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("input", {
                    defaultChecked: settings.theme === "dark",
                    name: "theme",
                    type: "radio",
                    value: "dark"
                  }),
                  " Dark"
                ],
                style: {
                  display: "inline-block"
                }
              })
            ],
            style: {
              border: "none",
              marginBottom: "1rem",
              padding: "0"
            }
          }),
          JsxRuntime.jsx("h3", {
            children: "Accessibility",
            style: {
              fontSize: "1.2rem",
              fontWeight: "600",
              margin: "1.5rem 0 1rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("span", {
                children: "Font Size (px)",
                style: {
                  display: "block",
                  fontWeight: "600",
                  marginBottom: "0.5rem"
                }
              }),
              JsxRuntime.jsx("input", {
                "aria-label": "Font size in pixels",
                defaultValue: String(settings.fontSize),
                style: {
                  backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                  border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                  color: isDark ? "#FFFFFF" : "#000000",
                  padding: "0.75rem",
                  width: "150px",
                  borderRadius: "4px"
                },
                max: "24",
                min: "12",
                type: "number"
              })
            ],
            style: {
              display: "block",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("input", {
                defaultChecked: settings.highContrast,
                type: "checkbox"
              }),
              " High contrast mode"
            ],
            style: {
              display: "block",
              marginBottom: "0.5rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("input", {
                defaultChecked: settings.reducedMotion,
                type: "checkbox"
              }),
              " Reduced motion"
            ],
            style: {
              display: "block",
              marginBottom: "0.5rem"
            }
          }),
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("input", {
                defaultChecked: settings.screenReaderMode,
                type: "checkbox"
              }),
              " Screen reader mode (extra announcements)"
            ],
            style: {
              display: "block",
              marginBottom: "1rem"
            }
          })
        ],
        "aria-labelledby": "ui-title",
        role: "region",
        style: {
          border: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
          marginBottom: "2rem",
          padding: "1.5rem",
          borderRadius: "8px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Reset to Defaults",
            "aria-label": "Reset all settings to default values",
            style: {
              backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
              border: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
              color: isDark ? "#FFFFFF" : "#000000",
              cursor: "pointer",
              fontWeight: "600",
              padding: "0.75rem 1.5rem",
              borderRadius: "6px"
            }
          }),
          JsxRuntime.jsx("button", {
            children: "Save",
            "aria-label": "Save settings",
            style: {
              backgroundColor: isDark ? "#66B2FF" : "#0052CC",
              border: "none",
              color: "white",
              cursor: "pointer",
              fontWeight: "600",
              padding: "0.75rem 1.5rem",
              borderRadius: "6px"
            }
          }),
          JsxRuntime.jsx("button", {
            children: "Cancel",
            "aria-label": "Cancel changes",
            style: {
              backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
              border: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
              color: isDark ? "#FFFFFF" : "#000000",
              cursor: "pointer",
              fontWeight: "600",
              padding: "0.75rem 1.5rem",
              borderRadius: "6px"
            }
          })
        ],
        style: {
          display: "flex",
          marginTop: "2rem",
          gap: "1rem"
        }
      })
    ],
    "aria-label": "Settings and preferences",
    role: "main",
    style: {
      backgroundColor: isDark ? "#000000" : "#FFFFFF",
      color: isDark ? "#FFFFFF" : "#000000",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      minHeight: "100vh",
      padding: "2rem"
    }
  });
}

let defaultSettings = {
  defaultRuntime: "Podman",
  defaultRegistry: "ghcr.io/hyperpolymath",
  autoVerifySignatures: true,
  requireSBOM: true,
  enforceNetworkPolicies: true,
  defaultCpuLimit: 1.0,
  defaultMemoryLimit: 512,
  defaultStorageLimit: 10,
  ctCliPath: "/usr/local/bin/ct",
  ctSigningKey: "~/.ct/keys/default.key",
  ctTransparencyLog: "https://rekor.sigstore.dev",
  ctBaseImage: "ghcr.io/hyperpolymath/base:latest",
  ctCompression: "zstd",
  ctAttestationFormat: "in-toto",
  svalinnEndpoint: "http://localhost:8000",
  svalinnAuth: "OAuth2",
  svalinnRequireVerified: true,
  svalinnBlockPrivileged: true,
  svalinnEnforceQuotas: true,
  svalinnAuditLogging: true,
  selurIpcMode: "ZeroCopyWASM",
  selurSharedMemory: 256,
  selurMaxThroughput: 10000,
  selurLatencyTarget: 1,
  vordrEndpoint: "http://localhost:8081",
  vordrProtocol: "JSON-RPC 2.0",
  vordrAutoRestart: true,
  vordrMaxRetries: 3,
  vordrBackoff: "exponential",
  theme: "system",
  fontSize: 16,
  highContrast: false,
  reducedMotion: false,
  screenReaderMode: false,
  gridSnapping: true,
  gridSize: 20,
  autoArrange: true
};

export {
  defaultSettings,
  view,
}
/* react/jsx-runtime Not a pure module */
