// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

let initialState = {
  hasError: false,
  error: undefined
};

function reducer(state, action) {
  if (typeof action !== "object") {
    return initialState;
  } else {
    return {
      hasError: true,
      error: action._0
    };
  }
}

function ErrorBoundary(props) {
  let onError = props.onError;
  let fallback = props.fallback;
  let match = React.useReducer(reducer, initialState);
  let dispatch = match[1];
  let state = match[0];
  React.useCallback((error, errorInfo) => {
    let errorMsg = error !== undefined ? String(Primitive_option.valFromOption(error)) : "Unknown error occurred";
    dispatch({
      TAG: "CatchError",
      _0: errorMsg
    });
    if (onError !== undefined) {
      onError(errorMsg);
    }
    console.error("Error caught by ErrorBoundary:", error);
    console.error("Error info:", errorInfo);
  }, [onError]);
  let handleReset = React.useCallback(() => dispatch("Reset"), []);
  if (!state.hasError) {
    return props.children;
  }
  if (fallback !== undefined) {
    return fallback;
  }
  let msg = state.error;
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h1", {
          children: "⚠️ Something went wrong",
          style: {
            fontSize: "2rem",
            fontWeight: "700",
            marginBottom: "1rem"
          }
        }),
        JsxRuntime.jsx("p", {
          children: msg !== undefined ? msg : "An unexpected error occurred. Please try refreshing the page.",
          style: {
            fontSize: "1rem",
            marginBottom: "2rem",
            opacity: "0.8"
          }
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("button", {
              children: "Try Again",
              "aria-label": "Try again",
              style: {
                backgroundColor: "#C53030",
                border: "none",
                color: "white",
                cursor: "pointer",
                fontSize: "1rem",
                fontWeight: "600",
                padding: "0.75rem 1.5rem",
                borderRadius: "6px"
              },
              onClick: param => handleReset()
            }),
            JsxRuntime.jsx("button", {
              children: "Go Home",
              "aria-label": "Go to home page",
              style: {
                backgroundColor: "white",
                border: "2px solid #C53030",
                color: "#C53030",
                cursor: "pointer",
                fontSize: "1rem",
                fontWeight: "600",
                padding: "0.75rem 1.5rem",
                borderRadius: "6px"
              },
              onClick: param => ((window.location.href = '/'))
            })
          ],
          style: {
            display: "flex",
            justifyContent: "center",
            gap: "1rem"
          }
        })
      ],
      style: {
        maxWidth: "600px",
        textAlign: "center"
      }
    }),
    "aria-live": "assertive",
    role: "alert",
    style: {
      backgroundColor: "#FFF5F5",
      color: "#C53030",
      display: "flex",
      minHeight: "100vh",
      padding: "2rem",
      alignItems: "center",
      flexDirection: "column",
      justifyContent: "center"
    }
  });
}

function wrap(children) {
  return JsxRuntime.jsx("make", {
    children: children
  });
}

let make = ErrorBoundary;

export {
  initialState,
  reducer,
  make,
  wrap,
}
/* react Not a pure module */
