// SPDX-License-Identifier: PMPL-1.0-or-later
// Export.res - Export designs to files

open Model
open DesignFormat

// Get current ISO timestamp
let getCurrentTimestamp = (): string => {
  let date = Js.Date.make()
  Js.Date.toISOString(date)
}

// Download a string as a file
let downloadFile = (filename: string, content: string, mimeType: string) => {
  // Create blob
  let blob = Webapi.Blob.makeFromString(
    content,
    {"type": mimeType},
  )

  // Create download link
  let url = Webapi.Url.createObjectURL(blob)
  let link = Webapi.Dom.document->Webapi.Dom.Document.createElement("a")

  link->Webapi.Dom.Element.setAttribute("href", url)
  link->Webapi.Dom.Element.setAttribute("download", filename)
  link->Webapi.Dom.HtmlElement.ofElement
    ->Belt.Option.forEach(htmlElement => {
      // Trigger download
      htmlElement->Webapi.Dom.HtmlElement.click
    })

  // Cleanup
  Webapi.Url.revokeObjectURL(url)
}

// Export design to JSON file
let exportDesignToJson = (model: model, description: string) => {
  let metadata: designMetadata = {
    version: currentVersion,
    created: getCurrentTimestamp(),
    author: "Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>",
    description: description,
  }

  let jsonString = serializeDesign(model, metadata)
  let timestamp = Js.Date.now()->Float.toString
  let filename = "stapeln-design-" ++ timestamp ++ ".json"

  downloadFile(filename, jsonString, "application/json")
  Js.Console.log("Exported design to " ++ filename)
}

// Export to compose.toml format
let exportToSelurCompose = (model: model) => {
  let toml = "# Generated by stapeln\n# TODO: Implement compose.toml generation\n\n"
    ++ "[stack]\n"
    ++ "name = \"my-stack\"\n"
    ++ "version = \"1.0\"\n\n"

  // Add services
  let services = model.components
    ->Array.map(comp => {
      "[[services]]\n"
      ++ "name = \"" ++ comp.id ++ "\"\n"
      ++ "type = \"" ++ componentTypeToString(comp.componentType) ++ "\"\n"
    })
    ->Array.joinWith("\n")

  let fullToml = toml ++ services

  let timestamp = Js.Date.now()->Float.toString
  let filename = "compose-" ++ timestamp ++ ".toml"

  downloadFile(filename, fullToml, "text/plain")
  Js.Console.log("Exported to " ++ filename)
}

// Export to docker-compose.yml format
let exportToDockerCompose = (model: model) => {
  let yaml = "# Generated by stapeln\n"
    ++ "version: '3.8'\n\n"
    ++ "services:\n"

  // Add services
  let services = model.components
    ->Array.map(comp => {
      "  " ++ comp.id ++ ":\n"
      ++ "    image: TODO\n"
      ++ "    # type: " ++ componentTypeToString(comp.componentType) ++ "\n"
    })
    ->Array.joinWith("\n")

  let fullYaml = yaml ++ services

  let timestamp = Js.Date.now()->Float.toString
  let filename = "docker-compose-" ++ timestamp ++ ".yml"

  downloadFile(filename, fullYaml, "text/yaml")
  Js.Console.log("Exported to " ++ filename)
}

// Export to podman-compose.yml format (same as docker-compose)
let exportToPodmanCompose = (model: model) => {
  exportToDockerCompose(model)
}
