// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as DesignFormat from "./DesignFormat.res.js";

function getCurrentTimestamp() {
  return new Date().toISOString();
}

function downloadFile(filename, content, mimeType) {
  let blob = new Blob([content], {
    type: mimeType
  });
  let url = URL.createObjectURL(blob);
  let link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  Belt_Option.forEach(link, htmlElement => {
    htmlElement.click();
  });
  URL.revokeObjectURL(url);
}

function exportDesignToJson(model, description) {
  let metadata_created = new Date().toISOString();
  let metadata = {
    version: DesignFormat.currentVersion,
    created: metadata_created,
    author: "Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>",
    description: description
  };
  let jsonString = DesignFormat.serializeDesign(model, metadata);
  let timestamp = String(Date.now());
  let filename = "stapeln-design-" + timestamp + ".json";
  downloadFile(filename, jsonString, "application/json");
  console.log("Exported design to " + filename);
}

function componentTypeToImage(ct) {
  switch (ct) {
    case "LagoGrey" :
      return "ghcr.io/hyperpolymath/lago-grey:latest";
    case "Svalinn" :
      return "ghcr.io/hyperpolymath/svalinn:latest";
    case "Selur" :
      return "ghcr.io/hyperpolymath/selur:latest";
    case "Vordr" :
      return "ghcr.io/hyperpolymath/vordr:latest";
    case "CerroTorre" :
    case "Podman" :
    case "Docker" :
    case "Nerdctl" :
      return "cgr.dev/chainguard/wolfi-base:latest";
    case "Volume" :
    case "Network" :
      return "busybox:latest";
  }
}

function exportToSelurCompose(model) {
  let toml = "# Generated by stapeln (selur-compose format)\n\n[stack]\nname = \"my-stack\"\nversion = \"1.0\"\n\n";
  let services = Belt_Array.map(model.components, comp => {
    let image = componentTypeToImage(comp.componentType);
    let port = comp.config["port"];
    let portLine = port !== undefined ? "port = " + port + "\n" : "";
    return "[[services]]\nname = \"" + comp.id + "\"\ntype = \"" + Model.componentTypeToString(comp.componentType) + "\"\nimage = \"" + image + "\"\n" + portLine;
  }).join("\n");
  let fullToml = toml + services;
  let timestamp = String(Date.now());
  let filename = "compose-" + timestamp + ".toml";
  downloadFile(filename, fullToml, "text/plain");
  console.log("Exported to " + filename);
}

function exportToDockerCompose(model) {
  let yaml = "# Generated by stapeln\nversion: '3.8'\n\nservices:\n";
  let services = Belt_Array.map(model.components, comp => {
    let image = componentTypeToImage(comp.componentType);
    let port = comp.config["port"];
    let portLine = port !== undefined ? "    ports:\n      - \"" + port + ":" + port + "\"\n" : "";
    return "  " + comp.id + ":\n    image: " + image + "\n    # type: " + Model.componentTypeToString(comp.componentType) + "\n" + portLine;
  }).join("\n");
  let fullYaml = yaml + services;
  let timestamp = String(Date.now());
  let filename = "docker-compose-" + timestamp + ".yml";
  downloadFile(filename, fullYaml, "text/yaml");
  console.log("Exported to " + filename);
}

let exportToPodmanCompose = exportToDockerCompose;

export {
  getCurrentTimestamp,
  downloadFile,
  exportDesignToJson,
  componentTypeToImage,
  exportToSelurCompose,
  exportToDockerCompose,
  exportToPodmanCompose,
}
/* DesignFormat Not a pure module */
