// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as DesignFormat from "./DesignFormat.res.js";

function getCurrentTimestamp() {
  return new Date().toISOString();
}

function downloadFile(filename, content, mimeType) {
  let blob = new Blob([content], {
    type: mimeType
  });
  let url = URL.createObjectURL(blob);
  let link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  Belt_Option.forEach(link, htmlElement => {
    htmlElement.click();
  });
  URL.revokeObjectURL(url);
}

function exportDesignToJson(model, description) {
  let metadata_created = new Date().toISOString();
  let metadata = {
    version: DesignFormat.currentVersion,
    created: metadata_created,
    author: "Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>",
    description: description
  };
  let jsonString = DesignFormat.serializeDesign(model, metadata);
  let timestamp = String(Date.now());
  let filename = "stapeln-design-" + timestamp + ".json";
  downloadFile(filename, jsonString, "application/json");
  console.log("Exported design to " + filename);
}

function exportToSelurCompose(model) {
  let toml = "# Generated by stapeln\n# TODO: Implement compose.toml generation\n\n[stack]\nname = \"my-stack\"\nversion = \"1.0\"\n\n";
  let services = Belt_Array.map(model.components, comp => "[[services]]\nname = \"" + comp.id + "\"\ntype = \"" + Model.componentTypeToString(comp.componentType) + "\"\n").join("\n");
  let fullToml = toml + services;
  let timestamp = String(Date.now());
  let filename = "compose-" + timestamp + ".toml";
  downloadFile(filename, fullToml, "text/plain");
  console.log("Exported to " + filename);
}

function exportToDockerCompose(model) {
  let yaml = "# Generated by stapeln\nversion: '3.8'\n\nservices:\n";
  let services = Belt_Array.map(model.components, comp => "  " + comp.id + ":\n    image: TODO\n    # type: " + Model.componentTypeToString(comp.componentType) + "\n").join("\n");
  let fullYaml = yaml + services;
  let timestamp = String(Date.now());
  let filename = "docker-compose-" + timestamp + ".yml";
  downloadFile(filename, fullYaml, "text/yaml");
  console.log("Exported to " + filename);
}

let exportToPodmanCompose = exportToDockerCompose;

export {
  getCurrentTimestamp,
  downloadFile,
  exportDesignToJson,
  exportToSelurCompose,
  exportToDockerCompose,
  exportToPodmanCompose,
}
/* No side effect */
