// Generated by ReScript, PLEASE EDIT WITH CARE


function resultFromInt(code) {
  switch (code) {
    case 0 :
      return "Success";
    case 1 :
      return "PathEmpty";
    case 2 :
      return "NotFound";
    case 3 :
      return "PermissionDenied";
    default:
      return "IOError";
  }
}

let FFI = {
  resultFromInt: resultFromInt
};

function readFile(path) {
  if (path.length === 0) {
    return {
      TAG: "Error",
      _0: "Path cannot be empty"
    };
  }
  if (!file_exists(path)) {
    return {
      TAG: "Error",
      _0: "File not found: " + path
    };
  }
  let code = read_file(path);
  let match = resultFromInt(code);
  switch (match) {
    case "Success" :
      return {
        TAG: "Ok",
        _0: "file contents"
      };
    case "PathEmpty" :
      return {
        TAG: "Error",
        _0: "Empty path"
      };
    case "NotFound" :
      return {
        TAG: "Error",
        _0: "File not found"
      };
    case "PermissionDenied" :
      return {
        TAG: "Error",
        _0: "Permission denied"
      };
    case "IOError" :
      return {
        TAG: "Error",
        _0: "I/O error"
      };
  }
}

function writeFile(path, content) {
  if (path.length === 0) {
    return {
      TAG: "Error",
      _0: "Path cannot be empty"
    };
  }
  let code = write_file(path, content);
  let match = resultFromInt(code);
  switch (match) {
    case "Success" :
      return {
        TAG: "Ok",
        _0: undefined
      };
    case "PathEmpty" :
      return {
        TAG: "Error",
        _0: "Empty path"
      };
    case "NotFound" :
      return {
        TAG: "Error",
        _0: "Directory not found"
      };
    case "PermissionDenied" :
      return {
        TAG: "Error",
        _0: "Permission denied"
      };
    case "IOError" :
      return {
        TAG: "Error",
        _0: "I/O error"
      };
  }
}

function exists(path) {
  if (path.length === 0) {
    return false;
  } else {
    return file_exists(path);
  }
}

function readFileWithCallback(path, onSuccess, onError) {
  let content = readFile(path);
  if (content.TAG === "Ok") {
    return onSuccess(content._0);
  } else {
    return onError(content._0);
  }
}

function writeFileWithCallback(path, content, onSuccess, onError) {
  let msg = writeFile(path, content);
  if (msg.TAG === "Ok") {
    return onSuccess();
  } else {
    return onError(msg._0);
  }
}

export {
  FFI,
  readFile,
  writeFile,
  exists,
  readFileWithCallback,
  writeFileWithCallback,
}
/* No side effect */
