// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js from "@rescript/runtime/lib/es6/Js.js";
import * as App from "./App.res.js";
import * as DomMounter from "./DomMounter.res.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

function init() {
  console.log("🚀 stapeln - Container Stack Designer");
  console.log("⚡ Powered by Idris² formal verification");
  console.log("");
  let msg = DomMounter.mountToApp();
  if (msg.TAG === "Ok") {
    console.log("✓ DOM element validated with formal proofs:");
    console.log("  - Memory safety: PROVEN");
    console.log("  - Thread safety: PROVEN");
    console.log("  - Type correctness: PROVEN");
    console.log("  - Element existence: VERIFIED");
    console.log("");
    let root = document.querySelector("#app");
    if (root == null) {
      console.error("❌ CRITICAL: #app element not found after validation");
      console.error("This should be impossible with formal proofs - please report this bug");
      return;
    }
    let reactRoot = Client.createRoot(root);
    reactRoot.render(JsxRuntime.jsx(App.make, {}));
    console.log("✓ React application mounted successfully");
    console.log("✓ All components initialized");
    return;
  }
  console.error("❌ Mount validation failed: " + msg._0);
  console.error("");
  console.error("Troubleshooting:");
  console.error("  1. Check that index.html contains <div id=\"app\"></div>");
  console.error("  2. Ensure no other script has removed the #app element");
  console.error("  3. Verify DOM is fully loaded before this script runs");
  console.error("");
  console.error("The formal verification system prevented mounting to an invalid target.");
  console.error("This is a safety feature - your application state is protected.");
}

let doc = Js.undefinedToOption(typeof document === "undefined" ? undefined : document);

if (doc !== undefined) {
  if ((doc.readyState === "loading")) {
    ((doc.addEventListener("DOMContentLoaded", function() { init() })));
  } else {
    init();
  }
} else {
  console.error("❌ Document object not available - are we in a browser?");
}

export {
  init,
}
/* doc Not a pure module */
