// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as LagoGreyExport from "./LagoGreyExport.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function formationName(formation) {
  return formation._0;
}

function formationSize(formation) {
  return formation._1;
}

function formationIcon(formation) {
  switch (formation.TAG) {
    case "Floe" :
      return "🧊";
    case "Iceberg" :
      return "🏔️";
    case "Glacier" :
      return "🌊";
  }
}

function formatBytes(bytes) {
  if (bytes < 1024) {
    return String(bytes) + " B";
  } else if (bytes < 1048576) {
    return String(bytes / 1024.0) + " KB";
  } else {
    return String(bytes / 1024.0 / 1024.0) + " MB";
  }
}

let availableFloes = [
  {
    TAG: "Floe",
    _0: "hello",
    _1: 29000
  },
  {
    TAG: "Floe",
    _0: "libsodium",
    _1: 506000
  },
  {
    TAG: "Floe",
    _0: "libargon2",
    _1: 42000
  },
  {
    TAG: "Floe",
    _0: "obli-pkg",
    _1: 56000
  }
];

let availableIcebergs = [{
    TAG: "Iceberg",
    _0: "liboqs",
    _1: 11000000
  }];

function LagoGreyImageDesigner(props) {
  let match = React.useState(() => ({
    baseImage: "Distroless",
    formations: [],
    totalSize: 10000000
  }));
  let setState = match[1];
  let state = match[0];
  let toggleFormation = formation => setState(prev => {
    let exists = Belt_Array.some(prev.formations, cf => formationName(cf.formation) === formationName(formation));
    if (exists) {
      return {
        baseImage: prev.baseImage,
        formations: Belt_Array.keep(prev.formations, cf => formationName(cf.formation) !== formationName(formation)),
        totalSize: prev.totalSize - formationSize(formation) | 0
      };
    } else {
      return {
        baseImage: prev.baseImage,
        formations: Belt_Array.concat(prev.formations, [{
            formation: formation,
            selected: false
          }]),
        totalSize: prev.totalSize + formationSize(formation) | 0
      };
    }
  });
  let setBaseImage = base => setState(prev => {
    let baseSize;
    switch (base) {
      case "Distroless" :
        baseSize = 10000000;
        break;
      case "Alpine" :
        baseSize = 60000000;
        break;
      case "Scratch" :
        baseSize = 0;
        break;
    }
    let formationsSize = Belt_Array.reduce(prev.formations, 0, (acc, cf) => acc + formationSize(cf.formation) | 0);
    return {
      baseImage: base,
      formations: prev.formations,
      totalSize: baseSize + formationsSize | 0
    };
  });
  let isFormationSelected = formation => Belt_Array.some(state.formations, cf => formationName(cf.formation) === formationName(formation));
  let match$1 = state.baseImage;
  let tmp;
  switch (match$1) {
    case "Distroless" :
      tmp = "Distroless Base";
      break;
    case "Alpine" :
      tmp = "Alpine Base";
      break;
    case "Scratch" :
      tmp = "Scratch (Empty)";
      break;
  }
  let match$2 = state.baseImage;
  let tmp$1;
  switch (match$2) {
    case "Distroless" :
      tmp$1 = "10 MB";
      break;
    case "Alpine" :
      tmp$1 = "60 MB";
      break;
    case "Scratch" :
      tmp$1 = "0 MB";
      break;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("header", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "🌊 Lago Grey Image Designer"
          }),
          JsxRuntime.jsx("p", {
            children: "Build minimal Linux distributions by assembling ice formations",
            className: "tagline"
          })
        ],
        className: "designer-header"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Base Image"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("button", {
                        children: [
                          JsxRuntime.jsx("div", {
                            children: "Distroless",
                            className: "base-name"
                          }),
                          JsxRuntime.jsx("div", {
                            children: "~10 MB, ~20 files",
                            className: "base-size"
                          })
                        ],
                        className: state.baseImage === "Distroless" ? "base-btn active" : "base-btn",
                        onClick: param => setBaseImage("Distroless")
                      }),
                      JsxRuntime.jsxs("button", {
                        children: [
                          JsxRuntime.jsx("div", {
                            children: "Alpine",
                            className: "base-name"
                          }),
                          JsxRuntime.jsx("div", {
                            children: "~60 MB, ~5,000 files",
                            className: "base-size"
                          })
                        ],
                        className: state.baseImage === "Alpine" ? "base-btn active" : "base-btn",
                        onClick: param => setBaseImage("Alpine")
                      }),
                      JsxRuntime.jsxs("button", {
                        children: [
                          JsxRuntime.jsx("div", {
                            children: "Scratch",
                            className: "base-name"
                          }),
                          JsxRuntime.jsx("div", {
                            children: "0 MB (empty)",
                            className: "base-size"
                          })
                        ],
                        className: state.baseImage === "Scratch" ? "base-btn active" : "base-btn",
                        onClick: param => setBaseImage("Scratch")
                      })
                    ],
                    className: "base-options"
                  })
                ],
                className: "section"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "🧊 Floes (< 1MB)"
                  }),
                  JsxRuntime.jsx("div", {
                    children: Belt_Array.map(availableFloes, floe => {
                      let selected = isFormationSelected(floe);
                      return JsxRuntime.jsxs("button", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: formationIcon(floe),
                            className: "component-icon"
                          }),
                          JsxRuntime.jsx("span", {
                            children: formationName(floe),
                            className: "component-name"
                          }),
                          JsxRuntime.jsx("span", {
                            children: formatBytes(formationSize(floe)),
                            className: "component-size"
                          })
                        ],
                        className: selected ? "component-btn selected" : "component-btn",
                        onClick: param => toggleFormation(floe)
                      }, formationName(floe));
                    }),
                    className: "component-list"
                  })
                ],
                className: "section"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "🏔️ Icebergs (1-75MB)"
                  }),
                  JsxRuntime.jsx("div", {
                    children: Belt_Array.map(availableIcebergs, iceberg => {
                      let selected = isFormationSelected(iceberg);
                      return JsxRuntime.jsxs("button", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: formationIcon(iceberg),
                            className: "component-icon"
                          }),
                          JsxRuntime.jsx("span", {
                            children: formationName(iceberg),
                            className: "component-name"
                          }),
                          JsxRuntime.jsx("span", {
                            children: formatBytes(formationSize(iceberg)),
                            className: "component-size"
                          })
                        ],
                        className: selected ? "component-btn selected" : "component-btn",
                        onClick: param => toggleFormation(iceberg)
                      }, formationName(iceberg));
                    }),
                    className: "component-list"
                  })
                ],
                className: "section"
              })
            ],
            className: "sidebar"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Your Lago Grey Image"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: "Total Size:",
                        className: "size-label"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formatBytes(state.totalSize),
                        className: "size-value"
                      }),
                      JsxRuntime.jsx("span", {
                        children: state.totalSize < 1000000 ? "🧊 Floe" : (
                            state.totalSize <= 75000000 ? "🏔️ Small Iceberg" : "🌊 Glacier"
                          ),
                        className: state.totalSize <= 17500000 ? "classification success" : "classification warning"
                      })
                    ],
                    className: "size-display"
                  })
                ],
                className: "canvas-header"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: "📦",
                        className: "layer-icon"
                      }),
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("div", {
                            children: tmp,
                            className: "layer-name"
                          }),
                          JsxRuntime.jsx("div", {
                            children: tmp$1,
                            className: "layer-size"
                          })
                        ],
                        className: "layer-info"
                      })
                    ],
                    className: "layer base-layer"
                  }),
                  Belt_Array.map(state.formations, cf => JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: formationIcon(cf.formation),
                        className: "layer-icon"
                      }),
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("div", {
                            children: formationName(cf.formation),
                            className: "layer-name"
                          }),
                          JsxRuntime.jsx("div", {
                            children: formatBytes(formationSize(cf.formation)),
                            className: "layer-size"
                          })
                        ],
                        className: "layer-info"
                      })
                    ],
                    className: "layer formation-layer"
                  }, formationName(cf.formation))),
                  state.formations.length === 0 ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                          children: "👈 Select components from the sidebar to add them"
                        }),
                        JsxRuntime.jsx("p", {
                          children: "Click on Floes or Icebergs to build your image",
                          className: "hint"
                        })
                      ],
                      className: "empty-state"
                    }) : null
                ],
                className: "canvas-content"
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("h3", {
                      children: "Competitive Position"
                    }),
                    JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("span", {
                              children: "vs Alpine (60 MB):",
                              className: "label"
                            }),
                            JsxRuntime.jsx("span", {
                              children: state.totalSize <= 60000000 ? String((1.0 - state.totalSize / 60000000) * 100.0) + "% smaller ✅" : String((state.totalSize / 60000000 - 1.0) * 100.0) + "% larger ⚠️",
                              className: "value"
                            })
                          ],
                          className: "comparison-item"
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("span", {
                              children: "Target (17.5 MB):",
                              className: "label"
                            }),
                            JsxRuntime.jsx("span", {
                              children: state.totalSize <= 17500000 ? "✅ Under target!" : "⚠️ " + formatBytes(state.totalSize - 17500000 | 0) + " over",
                              className: state.totalSize <= 17500000 ? "value success" : "value warning"
                            })
                          ],
                          className: "comparison-item"
                        })
                      ],
                      className: "comparison-grid"
                    })
                  ],
                  className: "comparison"
                }),
                className: "canvas-footer"
              })
            ],
            className: "canvas"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Ice Formation Guide"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: "🧊",
                            className: "guide-icon"
                          }),
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                children: "Floe",
                                className: "guide-title"
                              }),
                              JsxRuntime.jsx("div", {
                                children: "< 1MB - Small components",
                                className: "guide-desc"
                              })
                            ]
                          })
                        ],
                        className: "guide-item"
                      }),
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: "🏔️",
                            className: "guide-icon"
                          }),
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                children: "Iceberg",
                                className: "guide-title"
                              }),
                              JsxRuntime.jsx("div", {
                                children: "1-75MB - Medium chunks",
                                className: "guide-desc"
                              })
                            ]
                          })
                        ],
                        className: "guide-item"
                      }),
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: "🌊",
                            className: "guide-icon"
                          }),
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                children: "Glacier",
                                className: "guide-title"
                              }),
                              JsxRuntime.jsx("div", {
                                children: "75MB+ - Large masses",
                                className: "guide-desc"
                              })
                            ]
                          })
                        ],
                        className: "guide-item"
                      })
                    ],
                    className: "guide"
                  })
                ],
                className: "section"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Export"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("button", {
                        children: "📄 Dockerfile",
                        className: "export-btn",
                        onClick: param => {
                          let match = state.baseImage;
                          let tmp;
                          switch (match) {
                            case "Distroless" :
                              tmp = "Distroless";
                              break;
                            case "Alpine" :
                              tmp = "Alpine";
                              break;
                            case "Scratch" :
                              tmp = "Scratch";
                              break;
                          }
                          LagoGreyExport.exportDockerfile({
                            baseImage: tmp,
                            formations: Belt_Array.map(state.formations, cf => cf.formation),
                            totalSize: state.totalSize
                          });
                        }
                      }),
                      JsxRuntime.jsx("button", {
                        children: "📦 Complete Package",
                        className: "export-btn",
                        onClick: param => {
                          let match = state.baseImage;
                          let tmp;
                          switch (match) {
                            case "Distroless" :
                              tmp = "Distroless";
                              break;
                            case "Alpine" :
                              tmp = "Alpine";
                              break;
                            case "Scratch" :
                              tmp = "Scratch";
                              break;
                          }
                          LagoGreyExport.exportCompletePackage({
                            baseImage: tmp,
                            formations: Belt_Array.map(state.formations, cf => cf.formation),
                            totalSize: state.totalSize
                          });
                        }
                      }),
                      JsxRuntime.jsx("button", {
                        children: "📋 Manifest JSON",
                        className: "export-btn",
                        onClick: param => {
                          let match = state.baseImage;
                          let tmp;
                          switch (match) {
                            case "Distroless" :
                              tmp = "Distroless";
                              break;
                            case "Alpine" :
                              tmp = "Alpine";
                              break;
                            case "Scratch" :
                              tmp = "Scratch";
                              break;
                          }
                          LagoGreyExport.exportManifest({
                            baseImage: tmp,
                            formations: Belt_Array.map(state.formations, cf => cf.formation),
                            totalSize: state.totalSize
                          });
                        }
                      })
                    ],
                    className: "export-buttons"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "Click to download. Run 'podman build' to create image.",
                    className: "export-note"
                  })
                ],
                className: "section"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Security"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      isFormationSelected({
                        TAG: "Iceberg",
                        _0: "liboqs",
                        _1: 11000000
                      }) ? JsxRuntime.jsx("div", {
                          children: "✅ Post-quantum crypto",
                          className: "security-item enabled"
                        }) : JsxRuntime.jsx("div", {
                          children: "⚠️ No PQ crypto (add liboqs)",
                          className: "security-item disabled"
                        }),
                      isFormationSelected({
                        TAG: "Floe",
                        _0: "libsodium",
                        _1: 506000
                      }) ? JsxRuntime.jsx("div", {
                          children: "✅ Classical crypto",
                          className: "security-item enabled"
                        }) : JsxRuntime.jsx("div", {
                          children: "⚠️ No classical crypto",
                          className: "security-item disabled"
                        })
                    ],
                    className: "security-info"
                  })
                ],
                className: "section"
              })
            ],
            className: "info-panel"
          })
        ],
        className: "designer-layout"
      })
    ],
    className: "lago-grey-designer"
  });
}

let make = LagoGreyImageDesigner;

export {
  formationName,
  formationSize,
  formationIcon,
  formatBytes,
  availableFloes,
  availableIcebergs,
  make,
}
/* react Not a pure module */
