// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as LagoGreyExport from "./LagoGreyExport.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function formationName(formation) {
  return formation._0;
}

function formationSize(formation) {
  return formation._1;
}

function formationIcon(formation) {
  switch (formation.TAG) {
    case "Floe" :
      return "F";
    case "Iceberg" :
      return "I";
    case "Glacier" :
      return "G";
  }
}

function formationTypeLabel(formation) {
  switch (formation.TAG) {
    case "Floe" :
      return "Floe";
    case "Iceberg" :
      return "Iceberg";
    case "Glacier" :
      return "Glacier";
  }
}

function formatBytes(bytes) {
  if (bytes < 1024) {
    return String(bytes) + " B";
  }
  if (bytes < 1048576) {
    let kb = bytes / 1024.0;
    let rounded = (kb * 10.0 | 0) / 10.0;
    return String(rounded) + " KB";
  }
  let mb = bytes / 1024.0 / 1024.0;
  let rounded$1 = (mb * 100.0 | 0) / 100.0;
  return String(rounded$1) + " MB";
}

let availableFloes = [
  {
    TAG: "Floe",
    _0: "hello",
    _1: 29000
  },
  {
    TAG: "Floe",
    _0: "libsodium",
    _1: 506000
  },
  {
    TAG: "Floe",
    _0: "libargon2",
    _1: 42000
  },
  {
    TAG: "Floe",
    _0: "obli-pkg",
    _1: 56000
  },
  {
    TAG: "Floe",
    _0: "curl-minimal",
    _1: 280000
  },
  {
    TAG: "Floe",
    _0: "ca-certificates",
    _1: 200000
  }
];

let availableIcebergs = [
  {
    TAG: "Iceberg",
    _0: "liboqs",
    _1: 11000000
  },
  {
    TAG: "Iceberg",
    _0: "openssl",
    _1: 5000000
  },
  {
    TAG: "Iceberg",
    _0: "busybox",
    _1: 2000000
  }
];

let availableGlaciers = [
  {
    TAG: "Glacier",
    _0: "python-runtime",
    _1: 120000000
  },
  {
    TAG: "Glacier",
    _0: "nodejs-runtime",
    _1: 95000000
  }
];

function recalcSize(base, formations) {
  let baseSize;
  switch (base) {
    case "Distroless" :
      baseSize = 10000000;
      break;
    case "Alpine" :
      baseSize = 60000000;
      break;
    case "Scratch" :
      baseSize = 0;
      break;
  }
  let formationsSize = Belt_Array.reduce(formations, 0, (acc, cf) => acc + formationSize(cf.formation) | 0);
  return baseSize + formationsSize | 0;
}

function LagoGreyImageDesigner(props) {
  let match = React.useState(() => ({
    baseImage: "Distroless",
    formations: [],
    totalSize: 10000000,
    activeView: "Catalog",
    customName: "",
    customSize: 100000,
    customType: "floe",
    dragIndex: undefined,
    hoveredLayer: undefined
  }));
  let setState = match[1];
  let state = match[0];
  let toggleFormation = formation => setState(prev => {
    let exists = Belt_Array.some(prev.formations, cf => formationName(cf.formation) === formationName(formation));
    let newFormations = exists ? Belt_Array.keep(prev.formations, cf => formationName(cf.formation) !== formationName(formation)) : Belt_Array.concat(prev.formations, [{
          formation: formation,
          selected: false
        }]);
    return {
      baseImage: prev.baseImage,
      formations: newFormations,
      totalSize: recalcSize(prev.baseImage, newFormations),
      activeView: prev.activeView,
      customName: prev.customName,
      customSize: prev.customSize,
      customType: prev.customType,
      dragIndex: prev.dragIndex,
      hoveredLayer: prev.hoveredLayer
    };
  });
  let moveFormation = (fromIdx, toIdx) => setState(prev => {
    if (fromIdx === toIdx || fromIdx < 0 || toIdx < 0) {
      return prev;
    }
    let arr = prev.formations.slice(0);
    let item = Belt_Array.get(arr, fromIdx);
    if (item === undefined) {
      return prev;
    }
    let without = Belt_Array.keepWithIndex(arr, (_cf, i) => i !== fromIdx);
    let before = Belt_Array.slice(without, 0, toIdx);
    let after = Belt_Array.slice(without, toIdx, without.length - toIdx | 0);
    let newFormations = Belt_Array.concatMany([
      before,
      [item],
      after
    ]);
    return {
      baseImage: prev.baseImage,
      formations: newFormations,
      totalSize: prev.totalSize,
      activeView: prev.activeView,
      customName: prev.customName,
      customSize: prev.customSize,
      customType: prev.customType,
      dragIndex: undefined,
      hoveredLayer: undefined
    };
  });
  let addCustomFormation = () => setState(prev => {
    if (prev.customName === "") {
      return prev;
    }
    let match = prev.customType;
    let formation;
    switch (match) {
      case "glacier" :
        formation = {
          TAG: "Glacier",
          _0: prev.customName,
          _1: prev.customSize
        };
        break;
      case "iceberg" :
        formation = {
          TAG: "Iceberg",
          _0: prev.customName,
          _1: prev.customSize
        };
        break;
      default:
        formation = {
          TAG: "Floe",
          _0: prev.customName,
          _1: prev.customSize
        };
    }
    let newFormations = Belt_Array.concat(prev.formations, [{
        formation: formation,
        selected: false
      }]);
    return {
      baseImage: prev.baseImage,
      formations: newFormations,
      totalSize: recalcSize(prev.baseImage, newFormations),
      activeView: "Catalog",
      customName: "",
      customSize: 100000,
      customType: prev.customType,
      dragIndex: prev.dragIndex,
      hoveredLayer: prev.hoveredLayer
    };
  });
  let setBaseImage = base => setState(prev => ({
    baseImage: base,
    formations: prev.formations,
    totalSize: recalcSize(base, prev.formations),
    activeView: prev.activeView,
    customName: prev.customName,
    customSize: prev.customSize,
    customType: prev.customType,
    dragIndex: prev.dragIndex,
    hoveredLayer: prev.hoveredLayer
  }));
  let isFormationSelected = formation => Belt_Array.some(state.formations, cf => formationName(cf.formation) === formationName(formation));
  let sizeBarWidth = (size, maxSize) => {
    let pct = size / maxSize * 100.0;
    let clamped = Math.min(pct, 100.0);
    return String(clamped) + "%";
  };
  let match$1 = state.activeView;
  let tmp;
  switch (match$1) {
    case "Catalog" :
      tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Base Image"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: "Distroless",
                        className: "base-name"
                      }),
                      JsxRuntime.jsx("div", {
                        children: "~10 MB, ~20 files",
                        className: "base-size"
                      })
                    ],
                    className: state.baseImage === "Distroless" ? "base-btn active" : "base-btn",
                    onClick: param => setBaseImage("Distroless")
                  }),
                  JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: "Alpine",
                        className: "base-name"
                      }),
                      JsxRuntime.jsx("div", {
                        children: "~60 MB, ~5,000 files",
                        className: "base-size"
                      })
                    ],
                    className: state.baseImage === "Alpine" ? "base-btn active" : "base-btn",
                    onClick: param => setBaseImage("Alpine")
                  }),
                  JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: "Scratch",
                        className: "base-name"
                      }),
                      JsxRuntime.jsx("div", {
                        children: "0 MB (empty)",
                        className: "base-size"
                      })
                    ],
                    className: state.baseImage === "Scratch" ? "base-btn active" : "base-btn",
                    onClick: param => setBaseImage("Scratch")
                  })
                ],
                className: "base-options"
              })
            ],
            className: "section"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Floes (< 1MB)"
              }),
              JsxRuntime.jsx("div", {
                children: Belt_Array.map(availableFloes, floe => {
                  let selected = isFormationSelected(floe);
                  return JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: formationIcon(floe),
                        className: "component-icon"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formationName(floe),
                        className: "component-name"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formatBytes(formationSize(floe)),
                        className: "component-size"
                      })
                    ],
                    className: selected ? "component-btn selected" : "component-btn",
                    onClick: param => toggleFormation(floe)
                  }, formationName(floe));
                }),
                className: "component-list"
              })
            ],
            className: "section"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Icebergs (1-75MB)"
              }),
              JsxRuntime.jsx("div", {
                children: Belt_Array.map(availableIcebergs, iceberg => {
                  let selected = isFormationSelected(iceberg);
                  return JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: formationIcon(iceberg),
                        className: "component-icon"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formationName(iceberg),
                        className: "component-name"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formatBytes(formationSize(iceberg)),
                        className: "component-size"
                      })
                    ],
                    className: selected ? "component-btn selected" : "component-btn",
                    onClick: param => toggleFormation(iceberg)
                  }, formationName(iceberg));
                }),
                className: "component-list"
              })
            ],
            className: "section"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Glaciers (75MB+)"
              }),
              JsxRuntime.jsx("div", {
                children: Belt_Array.map(availableGlaciers, glacier => {
                  let selected = isFormationSelected(glacier);
                  return JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: formationIcon(glacier),
                        className: "component-icon"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formationName(glacier),
                        className: "component-name"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formatBytes(formationSize(glacier)),
                        className: "component-size"
                      })
                    ],
                    className: selected ? "component-btn selected" : "component-btn",
                    onClick: param => toggleFormation(glacier)
                  }, formationName(glacier));
                }),
                className: "component-list"
              })
            ],
            className: "section"
          })
        ]
      });
      break;
    case "LayerEditor" :
      tmp = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Layer Order"
          }),
          JsxRuntime.jsx("p", {
            children: "Click arrows to reorder. Click X to remove.",
            className: "hint",
            style: {
              fontSize: "0.85rem",
              marginBottom: "0.5rem",
              opacity: "0.7"
            }
          }),
          state.formations.length === 0 ? JsxRuntime.jsx("p", {
              children: "No formations added yet.",
              className: "empty-state"
            }) : JsxRuntime.jsx("div", {
              children: Belt_Array.mapWithIndex(state.formations, (idx, cf) => {
                let isHovered = state.hoveredLayer === idx;
                return JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                          children: "^",
                          "aria-label": "Move layer up",
                          style: {
                            background: "transparent",
                            border: "none",
                            color: "inherit",
                            cursor: idx === 0 ? "default" : "pointer",
                            opacity: idx === 0 ? "0.3" : "1",
                            padding: "0 4px"
                          },
                          disabled: idx === 0,
                          onClick: param => moveFormation(idx, idx - 1 | 0)
                        }),
                        JsxRuntime.jsx("button", {
                          children: "v",
                          "aria-label": "Move layer down",
                          style: {
                            background: "transparent",
                            border: "none",
                            color: "inherit",
                            cursor: idx === (state.formations.length - 1 | 0) ? "default" : "pointer",
                            opacity: idx === (state.formations.length - 1 | 0) ? "0.3" : "1",
                            padding: "0 4px"
                          },
                          disabled: idx === (state.formations.length - 1 | 0),
                          onClick: param => moveFormation(idx, idx + 1 | 0)
                        })
                      ],
                      style: {
                        display: "flex",
                        flexDirection: "column",
                        gap: "2px"
                      }
                    }),
                    JsxRuntime.jsx("span", {
                      children: formationIcon(cf.formation),
                      style: {
                        fontWeight: "600",
                        minWidth: "20px"
                      }
                    }),
                    JsxRuntime.jsx("span", {
                      children: formationName(cf.formation),
                      style: {
                        flex: "1"
                      }
                    }),
                    JsxRuntime.jsx("span", {
                      children: formatBytes(formationSize(cf.formation)),
                      style: {
                        fontSize: "0.85rem",
                        opacity: "0.6"
                      }
                    }),
                    JsxRuntime.jsx("button", {
                      children: "X",
                      "aria-label": "Remove " + formationName(cf.formation),
                      style: {
                        background: "transparent",
                        border: "none",
                        color: "#CC3333",
                        cursor: "pointer",
                        fontWeight: "bold",
                        padding: "2px 6px"
                      },
                      onClick: param => setState(prev => {
                        let newFormations = Belt_Array.keepWithIndex(prev.formations, (_cf, i) => i !== idx);
                        return {
                          baseImage: prev.baseImage,
                          formations: newFormations,
                          totalSize: recalcSize(prev.baseImage, newFormations),
                          activeView: prev.activeView,
                          customName: prev.customName,
                          customSize: prev.customSize,
                          customType: prev.customType,
                          dragIndex: prev.dragIndex,
                          hoveredLayer: prev.hoveredLayer
                        };
                      })
                    })
                  ],
                  className: isHovered ? "layer-editor-item hovered" : "layer-editor-item",
                  style: {
                    alignItems: "center",
                    borderBottom: "1px solid rgba(128,128,128,0.3)",
                    display: "flex",
                    gap: "0.5rem",
                    padding: "0.5rem"
                  },
                  onMouseEnter: param => setState(prev => ({
                    baseImage: prev.baseImage,
                    formations: prev.formations,
                    totalSize: prev.totalSize,
                    activeView: prev.activeView,
                    customName: prev.customName,
                    customSize: prev.customSize,
                    customType: prev.customType,
                    dragIndex: prev.dragIndex,
                    hoveredLayer: idx
                  })),
                  onMouseLeave: param => setState(prev => ({
                    baseImage: prev.baseImage,
                    formations: prev.formations,
                    totalSize: prev.totalSize,
                    activeView: prev.activeView,
                    customName: prev.customName,
                    customSize: prev.customSize,
                    customType: prev.customType,
                    dragIndex: prev.dragIndex,
                    hoveredLayer: undefined
                  }))
                }, formationName(cf.formation) + String(idx));
              }),
              className: "layer-editor-list"
            })
        ],
        className: "section"
      });
      break;
    case "CustomFormation" :
      tmp = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Add Custom Formation"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("label", {
                children: [
                  "Name",
                  JsxRuntime.jsx("input", {
                    style: {
                      background: "transparent",
                      border: "1px solid rgba(128,128,128,0.5)",
                      borderRadius: "4px",
                      color: "inherit",
                      marginTop: "0.25rem",
                      padding: "0.5rem",
                      width: "100%"
                    },
                    placeholder: "my-package",
                    type: "text",
                    value: state.customName,
                    onChange: e => {
                      let value = e.target.value;
                      setState(prev => ({
                        baseImage: prev.baseImage,
                        formations: prev.formations,
                        totalSize: prev.totalSize,
                        activeView: prev.activeView,
                        customName: value,
                        customSize: prev.customSize,
                        customType: prev.customType,
                        dragIndex: prev.dragIndex,
                        hoveredLayer: prev.hoveredLayer
                      }));
                    }
                  })
                ]
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  "Size (bytes)",
                  JsxRuntime.jsx("input", {
                    style: {
                      background: "transparent",
                      border: "1px solid rgba(128,128,128,0.5)",
                      borderRadius: "4px",
                      color: "inherit",
                      marginTop: "0.25rem",
                      padding: "0.5rem",
                      width: "100%"
                    },
                    min: "1",
                    type: "number",
                    value: String(state.customSize),
                    onChange: e => {
                      let value = e.target.value;
                      let n = Belt_Int.fromString(value);
                      let size = n !== undefined ? n : 0;
                      setState(prev => ({
                        baseImage: prev.baseImage,
                        formations: prev.formations,
                        totalSize: prev.totalSize,
                        activeView: prev.activeView,
                        customName: prev.customName,
                        customSize: size,
                        customType: prev.customType,
                        dragIndex: prev.dragIndex,
                        hoveredLayer: prev.hoveredLayer
                      }));
                    }
                  })
                ]
              }),
              JsxRuntime.jsxs("label", {
                children: [
                  "Type",
                  JsxRuntime.jsxs("select", {
                    children: [
                      JsxRuntime.jsx("option", {
                        children: "Floe (< 1MB)",
                        value: "floe"
                      }),
                      JsxRuntime.jsx("option", {
                        children: "Iceberg (1-75MB)",
                        value: "iceberg"
                      }),
                      JsxRuntime.jsx("option", {
                        children: "Glacier (75MB+)",
                        value: "glacier"
                      })
                    ],
                    style: {
                      background: "transparent",
                      border: "1px solid rgba(128,128,128,0.5)",
                      borderRadius: "4px",
                      color: "inherit",
                      marginTop: "0.25rem",
                      padding: "0.5rem",
                      width: "100%"
                    },
                    value: state.customType,
                    onChange: e => {
                      let value = e.target.value;
                      setState(prev => ({
                        baseImage: prev.baseImage,
                        formations: prev.formations,
                        totalSize: prev.totalSize,
                        activeView: prev.activeView,
                        customName: prev.customName,
                        customSize: prev.customSize,
                        customType: value,
                        dragIndex: prev.dragIndex,
                        hoveredLayer: prev.hoveredLayer
                      }));
                    }
                  })
                ]
              }),
              JsxRuntime.jsx("button", {
                children: "Add Formation",
                className: "export-btn",
                disabled: state.customName === "",
                onClick: param => addCustomFormation()
              })
            ],
            style: {
              display: "flex",
              flexDirection: "column",
              gap: "0.75rem"
            }
          })
        ],
        className: "section"
      });
      break;
  }
  let match$2 = state.baseImage;
  let tmp$1;
  switch (match$2) {
    case "Distroless" :
      tmp$1 = "Distroless Base";
      break;
    case "Alpine" :
      tmp$1 = "Alpine Base";
      break;
    case "Scratch" :
      tmp$1 = "Scratch (Empty)";
      break;
  }
  let match$3 = state.baseImage;
  let tmp$2;
  switch (match$3) {
    case "Distroless" :
      tmp$2 = "10 MB";
      break;
    case "Alpine" :
      tmp$2 = "60 MB";
      break;
    case "Scratch" :
      tmp$2 = "0 MB";
      break;
  }
  let match$4 = state.baseImage;
  let tmp$3;
  switch (match$4) {
    case "Distroless" :
      tmp$3 = 10000000;
      break;
    case "Alpine" :
      tmp$3 = 60000000;
      break;
    case "Scratch" :
      tmp$3 = 0;
      break;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("header", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "Lago Grey Image Designer"
          }),
          JsxRuntime.jsx("p", {
            children: "Build minimal Linux distributions by assembling ice formations",
            className: "tagline"
          })
        ],
        className: "designer-header"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("button", {
                    children: "Catalog",
                    className: state.activeView === "Catalog" ? "tab-btn active" : "tab-btn",
                    onClick: param => setState(prev => ({
                      baseImage: prev.baseImage,
                      formations: prev.formations,
                      totalSize: prev.totalSize,
                      activeView: "Catalog",
                      customName: prev.customName,
                      customSize: prev.customSize,
                      customType: prev.customType,
                      dragIndex: prev.dragIndex,
                      hoveredLayer: prev.hoveredLayer
                    }))
                  }),
                  JsxRuntime.jsx("button", {
                    children: "Layers",
                    className: state.activeView === "LayerEditor" ? "tab-btn active" : "tab-btn",
                    onClick: param => setState(prev => ({
                      baseImage: prev.baseImage,
                      formations: prev.formations,
                      totalSize: prev.totalSize,
                      activeView: "LayerEditor",
                      customName: prev.customName,
                      customSize: prev.customSize,
                      customType: prev.customType,
                      dragIndex: prev.dragIndex,
                      hoveredLayer: prev.hoveredLayer
                    }))
                  }),
                  JsxRuntime.jsx("button", {
                    children: "+ Custom",
                    className: state.activeView === "CustomFormation" ? "tab-btn active" : "tab-btn",
                    onClick: param => setState(prev => ({
                      baseImage: prev.baseImage,
                      formations: prev.formations,
                      totalSize: prev.totalSize,
                      activeView: "CustomFormation",
                      customName: prev.customName,
                      customSize: prev.customSize,
                      customType: prev.customType,
                      dragIndex: prev.dragIndex,
                      hoveredLayer: prev.hoveredLayer
                    }))
                  })
                ],
                className: "view-tabs",
                style: {
                  display: "flex",
                  gap: "0.25rem",
                  marginBottom: "1rem"
                }
              }),
              tmp
            ],
            className: "sidebar"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Your Lago Grey Image"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("span", {
                        children: "Total Size:",
                        className: "size-label"
                      }),
                      JsxRuntime.jsx("span", {
                        children: formatBytes(state.totalSize),
                        className: "size-value"
                      }),
                      JsxRuntime.jsx("span", {
                        children: state.totalSize < 1000000 ? "Floe" : (
                            state.totalSize <= 75000000 ? "Small Iceberg" : "Glacier"
                          ),
                        className: state.totalSize <= 17500000 ? "classification success" : "classification warning"
                      })
                    ],
                    className: "size-display"
                  })
                ],
                className: "canvas-header"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: "B",
                        className: "layer-icon"
                      }),
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("div", {
                            children: tmp$1,
                            className: "layer-name"
                          }),
                          JsxRuntime.jsx("div", {
                            children: tmp$2,
                            className: "layer-size"
                          })
                        ],
                        className: "layer-info"
                      }),
                      JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx("div", {
                          style: {
                            backgroundColor: "#4CAF50",
                            borderRadius: "2px",
                            height: "4px",
                            width: sizeBarWidth(tmp$3, Math.max(state.totalSize, 1))
                          }
                        }),
                        style: {
                          backgroundColor: "rgba(128,128,128,0.2)",
                          borderRadius: "2px",
                          height: "4px",
                          marginTop: "4px",
                          width: "100%"
                        }
                      })
                    ],
                    className: "layer base-layer"
                  }),
                  Belt_Array.mapWithIndex(state.formations, (idx, cf) => {
                    let match = cf.formation;
                    let tmp;
                    switch (match.TAG) {
                      case "Floe" :
                        tmp = "#2196F3";
                        break;
                      case "Iceberg" :
                        tmp = "#FF9800";
                        break;
                      case "Glacier" :
                        tmp = "#F44336";
                        break;
                    }
                    return JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                          children: formationIcon(cf.formation),
                          className: "layer-icon"
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                              children: formationName(cf.formation) + " (" + formationTypeLabel(cf.formation) + ")",
                              className: "layer-name"
                            }),
                            JsxRuntime.jsx("div", {
                              children: formatBytes(formationSize(cf.formation)),
                              className: "layer-size"
                            })
                          ],
                          className: "layer-info"
                        }),
                        JsxRuntime.jsx("div", {
                          children: JsxRuntime.jsx("div", {
                            style: {
                              backgroundColor: tmp,
                              borderRadius: "2px",
                              height: "4px",
                              width: sizeBarWidth(formationSize(cf.formation), Math.max(state.totalSize, 1))
                            }
                          }),
                          style: {
                            backgroundColor: "rgba(128,128,128,0.2)",
                            borderRadius: "2px",
                            height: "4px",
                            marginTop: "4px",
                            width: "100%"
                          }
                        })
                      ],
                      className: "layer formation-layer"
                    }, formationName(cf.formation) + String(idx));
                  }),
                  state.formations.length === 0 ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                          children: "Select components from the sidebar to add them"
                        }),
                        JsxRuntime.jsx("p", {
                          children: "Click on Floes, Icebergs, or Glaciers to build your image",
                          className: "hint"
                        })
                      ],
                      className: "empty-state"
                    }) : null
                ],
                className: "canvas-content"
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("h3", {
                      children: "Competitive Position"
                    }),
                    JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("span", {
                              children: "vs Alpine (60 MB):",
                              className: "label"
                            }),
                            JsxRuntime.jsx("span", {
                              children: state.totalSize <= 60000000 ? String((1.0 - state.totalSize / 60000000) * 100.0) + "% smaller" : String((state.totalSize / 60000000 - 1.0) * 100.0) + "% larger",
                              className: "value"
                            })
                          ],
                          className: "comparison-item"
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("span", {
                              children: "Target (17.5 MB):",
                              className: "label"
                            }),
                            JsxRuntime.jsx("span", {
                              children: state.totalSize <= 17500000 ? "Under target!" : formatBytes(state.totalSize - 17500000 | 0) + " over",
                              className: state.totalSize <= 17500000 ? "value success" : "value warning"
                            })
                          ],
                          className: "comparison-item"
                        })
                      ],
                      className: "comparison-grid"
                    })
                  ],
                  className: "comparison"
                }),
                className: "canvas-footer"
              })
            ],
            className: "canvas"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Ice Formation Guide"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: "F",
                            className: "guide-icon"
                          }),
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                children: "Floe",
                                className: "guide-title"
                              }),
                              JsxRuntime.jsx("div", {
                                children: "< 1MB - Small components",
                                className: "guide-desc"
                              })
                            ]
                          })
                        ],
                        className: "guide-item"
                      }),
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: "I",
                            className: "guide-icon"
                          }),
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                children: "Iceberg",
                                className: "guide-title"
                              }),
                              JsxRuntime.jsx("div", {
                                children: "1-75MB - Medium chunks",
                                className: "guide-desc"
                              })
                            ]
                          })
                        ],
                        className: "guide-item"
                      }),
                      JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("span", {
                            children: "G",
                            className: "guide-icon"
                          }),
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                children: "Glacier",
                                className: "guide-title"
                              }),
                              JsxRuntime.jsx("div", {
                                children: "75MB+ - Large masses",
                                className: "guide-desc"
                              })
                            ]
                          })
                        ],
                        className: "guide-item"
                      })
                    ],
                    className: "guide"
                  })
                ],
                className: "section"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Export"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("button", {
                        children: "Containerfile",
                        className: "export-btn",
                        onClick: param => {
                          let match = state.baseImage;
                          let tmp;
                          switch (match) {
                            case "Distroless" :
                              tmp = "Distroless";
                              break;
                            case "Alpine" :
                              tmp = "Alpine";
                              break;
                            case "Scratch" :
                              tmp = "Scratch";
                              break;
                          }
                          LagoGreyExport.exportDockerfile({
                            baseImage: tmp,
                            formations: Belt_Array.map(state.formations, cf => cf.formation),
                            totalSize: state.totalSize
                          });
                        }
                      }),
                      JsxRuntime.jsx("button", {
                        children: "Complete Package",
                        className: "export-btn",
                        onClick: param => {
                          let match = state.baseImage;
                          let tmp;
                          switch (match) {
                            case "Distroless" :
                              tmp = "Distroless";
                              break;
                            case "Alpine" :
                              tmp = "Alpine";
                              break;
                            case "Scratch" :
                              tmp = "Scratch";
                              break;
                          }
                          LagoGreyExport.exportCompletePackage({
                            baseImage: tmp,
                            formations: Belt_Array.map(state.formations, cf => cf.formation),
                            totalSize: state.totalSize
                          });
                        }
                      }),
                      JsxRuntime.jsx("button", {
                        children: "Manifest JSON",
                        className: "export-btn",
                        onClick: param => {
                          let match = state.baseImage;
                          let tmp;
                          switch (match) {
                            case "Distroless" :
                              tmp = "Distroless";
                              break;
                            case "Alpine" :
                              tmp = "Alpine";
                              break;
                            case "Scratch" :
                              tmp = "Scratch";
                              break;
                          }
                          LagoGreyExport.exportManifest({
                            baseImage: tmp,
                            formations: Belt_Array.map(state.formations, cf => cf.formation),
                            totalSize: state.totalSize
                          });
                        }
                      })
                    ],
                    className: "export-buttons"
                  }),
                  JsxRuntime.jsx("p", {
                    children: "Click to download. Run 'podman build' to create image.",
                    className: "export-note"
                  })
                ],
                className: "section"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Security"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      isFormationSelected({
                        TAG: "Iceberg",
                        _0: "liboqs",
                        _1: 11000000
                      }) ? JsxRuntime.jsx("div", {
                          children: "[OK] Post-quantum crypto",
                          className: "security-item enabled"
                        }) : JsxRuntime.jsx("div", {
                          children: "[--] No PQ crypto (add liboqs)",
                          className: "security-item disabled"
                        }),
                      isFormationSelected({
                        TAG: "Floe",
                        _0: "libsodium",
                        _1: 506000
                      }) ? JsxRuntime.jsx("div", {
                          children: "[OK] Classical crypto",
                          className: "security-item enabled"
                        }) : JsxRuntime.jsx("div", {
                          children: "[--] No classical crypto",
                          className: "security-item disabled"
                        }),
                      isFormationSelected({
                        TAG: "Floe",
                        _0: "ca-certificates",
                        _1: 200000
                      }) ? JsxRuntime.jsx("div", {
                          children: "[OK] CA certificates",
                          className: "security-item enabled"
                        }) : JsxRuntime.jsx("div", {
                          children: "[--] No CA certs (add ca-certificates)",
                          className: "security-item disabled"
                        })
                    ],
                    className: "security-info"
                  })
                ],
                className: "section"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h2", {
                    children: "Layer Summary"
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("p", {
                        children: "Layers: " + String(state.formations.length + 1 | 0)
                      }),
                      JsxRuntime.jsx("p", {
                        children: "Formations: " + String(state.formations.length)
                      }),
                      JsxRuntime.jsx("p", {
                        children: "Floes: " + String(Belt_Array.reduce(state.formations, 0, (acc, cf) => {
                          let match = cf.formation;
                          switch (match.TAG) {
                            case "Floe" :
                              return acc + 1 | 0;
                            case "Iceberg" :
                            case "Glacier" :
                              return acc;
                          }
                        }))
                      }),
                      JsxRuntime.jsx("p", {
                        children: "Icebergs: " + String(Belt_Array.reduce(state.formations, 0, (acc, cf) => {
                          let match = cf.formation;
                          switch (match.TAG) {
                            case "Iceberg" :
                              return acc + 1 | 0;
                            case "Floe" :
                            case "Glacier" :
                              return acc;
                          }
                        }))
                      }),
                      JsxRuntime.jsx("p", {
                        children: "Glaciers: " + String(Belt_Array.reduce(state.formations, 0, (acc, cf) => {
                          let match = cf.formation;
                          switch (match.TAG) {
                            case "Floe" :
                            case "Iceberg" :
                              return acc;
                            case "Glacier" :
                              return acc + 1 | 0;
                          }
                        }))
                      })
                    ],
                    style: {
                      fontSize: "0.85rem"
                    }
                  })
                ],
                className: "section"
              })
            ],
            className: "info-panel"
          })
        ],
        className: "designer-layout"
      })
    ],
    className: "lago-grey-designer"
  });
}

let make = LagoGreyImageDesigner;

export {
  formationName,
  formationSize,
  formationIcon,
  formationTypeLabel,
  formatBytes,
  availableFloes,
  availableIcebergs,
  availableGlaciers,
  recalcSize,
  make,
}
/* react Not a pure module */
