// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketMathWasmJs from "./PacketMathWasm.js";

function lerpQ16Unsafe(prim0, prim1, prim2) {
  return PacketMathWasmJs.lerpQ16(prim0, prim1, prim2);
}

function isWasmActive(prim) {
  return PacketMathWasmJs.isWasmActive();
}

function addQ16Unsafe(prim0, prim1) {
  return PacketMathWasmJs.addQ16(prim0, prim1);
}

function isAddWasmActive(prim) {
  return PacketMathWasmJs.isAddWasmActive();
}

function clampInt(value, minValue, maxValue) {
  if (value < minValue) {
    return minValue;
  } else if (value > maxValue) {
    return maxValue;
  } else {
    return value;
  }
}

function toFixedCoord(coord) {
  return coord * 1024.0 | 0;
}

function fromFixedCoord(coord) {
  return coord / 1024.0;
}

function toProgressQ16(progress) {
  let raw = progress * 65536.0 | 0;
  return clampInt(raw, 0, 65536);
}

function advanceProgress(progress, step) {
  let progressQ16 = toProgressQ16(progress);
  let stepQ16 = toProgressQ16(step);
  let nextQ16Raw = PacketMathWasmJs.addQ16(progressQ16, stepQ16);
  let nextQ16 = clampInt(nextQ16Raw, 0, 65536);
  return {
    progress: nextQ16 / 65536.0,
    arrived: nextQ16 >= 65536
  };
}

function lerpCoordinate(source, target, progress) {
  let sourceFixed = source * 1024.0 | 0;
  let targetFixed = target * 1024.0 | 0;
  let progressQ16 = toProgressQ16(progress);
  let coord = PacketMathWasmJs.lerpQ16(sourceFixed, targetFixed, progressQ16);
  return coord / 1024.0;
}

function lerpPosition(source, target, progress) {
  return [
    lerpCoordinate(source[0], target[0], progress),
    lerpCoordinate(source[1], target[1], progress)
  ];
}

let coordScale = 1024.0;

let progressScale = 65536.0;

let maxProgressQ16 = 65536;

export {
  lerpQ16Unsafe,
  isWasmActive,
  addQ16Unsafe,
  isAddWasmActive,
  coordScale,
  progressScale,
  maxProgressQ16,
  clampInt,
  toFixedCoord,
  fromFixedCoord,
  toProgressQ16,
  advanceProgress,
  lerpCoordinate,
  lerpPosition,
}
/* ./PacketMathWasm.js Not a pure module */
