// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DomMounterEnhanced from "./DomMounterEnhanced.res.js";
import * as DomMounterSecurity from "./DomMounterSecurity.res.js";

function useDomMounter(elementId) {
  let match = React.useState(() => false);
  let setMounted = match[1];
  let match$1 = React.useState(() => {});
  let setError = match$1[1];
  React.useEffect(() => {
    let msg = DomMounterEnhanced.mount(elementId);
    if (msg.TAG === "Ok") {
      setMounted(param => true);
    } else {
      let msg$1 = msg._0;
      setError(param => msg$1);
    }
    return () => {
      setMounted(param => false);
      setError(param => {});
    };
  }, [elementId]);
  return [
    match[0],
    match$1[0]
  ];
}

function useDomMounterWithHooks(elementId, beforeMount, afterMount, beforeUnmount, afterUnmount, onError, param) {
  let match = React.useState(() => false);
  let setMounted = match[1];
  let match$1 = React.useState(() => {});
  let setError = match$1[1];
  React.useEffect(() => {
    let hooks = {
      beforeMount: beforeMount,
      afterMount: afterMount,
      beforeUnmount: beforeUnmount,
      afterUnmount: afterUnmount,
      onError: onError
    };
    let msg = DomMounterEnhanced.mountWithLifecycle(elementId, hooks);
    if (msg.TAG === "Ok") {
      setMounted(param => true);
    } else {
      let msg$1 = msg._0;
      setError(param => msg$1);
    }
    return () => {
      DomMounterEnhanced.unmountWithLifecycle(elementId, hooks);
      setMounted(param => false);
    };
  }, [elementId]);
  return [
    match[0],
    match$1[0]
  ];
}

function useDomMounterSecure(elementId, policy) {
  let match = React.useState(() => false);
  let setMounted = match[1];
  let match$1 = React.useState(() => {});
  let setError = match$1[1];
  React.useEffect(() => {
    let securityPolicy = policy !== undefined ? policy : DomMounterSecurity.defaultSecurityPolicy;
    let msg = DomMounterSecurity.mountWithPolicy(elementId, securityPolicy);
    if (msg.TAG === "Ok") {
      setMounted(param => true);
    } else {
      let msg$1 = msg._0;
      setError(param => msg$1);
    }
    return () => setMounted(param => false);
  }, [elementId]);
  return [
    match[0],
    match$1[0]
  ];
}

function useDomMounterMonitored(elementId) {
  let match = React.useState(() => false);
  let setMounted = match[1];
  let match$1 = React.useState(() => {});
  let setError = match$1[1];
  let match$2 = React.useState(() => "Healthy");
  let setHealth = match$2[1];
  React.useEffect(() => {
    DomMounterEnhanced.startMonitoring(elementId);
    let msg = DomMounterEnhanced.mount(elementId);
    if (msg.TAG === "Ok") {
      setMounted(param => true);
    } else {
      let msg$1 = msg._0;
      setError(param => msg$1);
    }
    let intervalId = setInterval(() => {
      let match = DomMounterEnhanced.healthCheck(elementId);
      let healthStatus = match[0];
      setHealth(param => healthStatus);
    }, 5000);
    return () => {
      clearInterval(intervalId);
      DomMounterEnhanced.stopMonitoring(elementId);
      setMounted(param => false);
    };
  }, [elementId]);
  return [
    match[0],
    match$1[0],
    match$2[0]
  ];
}

export {
  useDomMounter,
  useDomMounterWithHooks,
  useDomMounterSecure,
  useDomMounterMonitored,
}
/* react Not a pure module */
