// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as PacketMathWasm from "./PacketMathWasm.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function keepLastN(items, maxCount) {
  let overflow = items.length - maxCount | 0;
  if (overflow <= 0) {
    return [
      items,
      0
    ];
  } else {
    return [
      Belt_Array.keepWithIndex(items, (param, idx) => idx >= overflow),
      overflow
    ];
  }
}

function enforcePacketCap(packets) {
  return keepLastN(packets, 2000);
}

function enforceEventCap(events) {
  return keepLastN(events, 1000);
}

function stepPacketsKernel(packets, nodesById, step) {
  return Belt_Array.map(packets, packet => {
    let match = packet.status;
    switch (match) {
      case "InTransit" :
        let progressUpdate = PacketMathWasm.advanceProgress(packet.progress, step);
        let newProgress = progressUpdate.progress;
        if (progressUpdate.arrived) {
          return {
            id: packet.id,
            packetType: packet.packetType,
            status: "Delivered",
            sourceNode: packet.sourceNode,
            targetNode: packet.targetNode,
            payload: packet.payload,
            size: packet.size,
            encrypted: packet.encrypted,
            timestamp: packet.timestamp,
            progress: 1.0,
            position: packet.position
          };
        }
        let sourceNode = Js_dict.get(nodesById, packet.sourceNode);
        let targetNode = Js_dict.get(nodesById, packet.targetNode);
        if (sourceNode !== undefined && targetNode !== undefined) {
          let match$1 = PacketMathWasm.lerpPosition([
            sourceNode.x,
            sourceNode.y
          ], [
            targetNode.x,
            targetNode.y
          ], newProgress);
          return {
            id: packet.id,
            packetType: packet.packetType,
            status: packet.status,
            sourceNode: packet.sourceNode,
            targetNode: packet.targetNode,
            payload: packet.payload,
            size: packet.size,
            encrypted: packet.encrypted,
            timestamp: packet.timestamp,
            progress: newProgress,
            position: [
              match$1[0],
              match$1[1]
            ]
          };
        }
        return {
          id: packet.id,
          packetType: packet.packetType,
          status: packet.status,
          sourceNode: packet.sourceNode,
          targetNode: packet.targetNode,
          payload: packet.payload,
          size: packet.size,
          encrypted: packet.encrypted,
          timestamp: packet.timestamp,
          progress: newProgress,
          position: packet.position
        };
        break;
      case "Delivered" :
        return {
          id: packet.id,
          packetType: packet.packetType,
          status: packet.status,
          sourceNode: packet.sourceNode,
          targetNode: packet.targetNode,
          payload: packet.payload,
          size: packet.size,
          encrypted: packet.encrypted,
          timestamp: packet.timestamp,
          progress: PacketMathWasm.advanceProgress(packet.progress, step).progress,
          position: packet.position
        };
      case "Dropped" :
      case "Blocked" :
        return packet;
    }
  });
}

let init_nodes = [
  {
    id: "node-1",
    name: "API Gateway",
    x: 150.0,
    y: 250.0
  },
  {
    id: "node-2",
    name: "Auth Service",
    x: 450.0,
    y: 250.0
  },
  {
    id: "node-3",
    name: "PostgreSQL",
    x: 750.0,
    y: 250.0
  },
  {
    id: "node-4",
    name: "Redis Cache",
    x: 450.0,
    y: 100.0
  },
  {
    id: "node-5",
    name: "Load Balancer",
    x: 300.0,
    y: 400.0
  }
];

let init_packets = [];

let init_events = [];

let init = {
  nodes: init_nodes,
  packets: init_packets,
  events: init_events,
  isRunning: false,
  speed: "Normal",
  mode: "PacketView",
  currentTime: 0.0,
  totalPacketsSent: 0,
  totalPacketsDelivered: 0,
  totalPacketsDropped: 0,
  avgLatency: 0.0,
  showStats: true,
  selectedPacket: undefined,
  showEventLog: true
};

function update(msg, state) {
  if (typeof msg !== "object") {
    switch (msg) {
      case "StartSimulation" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: state.events,
          isRunning: true,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "PauseSimulation" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: state.events,
          isRunning: false,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "StopSimulation" :
        return {
          nodes: state.nodes,
          packets: [],
          events: [],
          isRunning: false,
          speed: state.speed,
          mode: state.mode,
          currentTime: 0.0,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "ToggleStats" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: state.events,
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: !state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "ToggleEventLog" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: state.events,
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: !state.showEventLog
        };
      case "ClearEvents" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: [],
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
    }
  } else {
    switch (msg.TAG) {
      case "SetSpeed" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: state.events,
          isRunning: state.isRunning,
          speed: msg._0,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "SetMode" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: state.events,
          isRunning: state.isRunning,
          speed: state.speed,
          mode: msg._0,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "SendPacket" :
        let packetType = msg._2;
        let targetId = msg._1;
        let sourceId = msg._0;
        let sourceNode = Belt_Array.getBy(state.nodes, n => n.id === sourceId);
        let targetNode = Belt_Array.getBy(state.nodes, n => n.id === targetId);
        if (sourceNode === undefined) {
          return state;
        }
        if (targetNode === undefined) {
          return state;
        }
        let packetId = "packet-" + String(Date.now());
        let newPacket_encrypted = packetType === "HTTPS";
        let newPacket_timestamp = state.currentTime;
        let newPacket_position = [
          sourceNode.x,
          sourceNode.y
        ];
        let newPacket = {
          id: packetId,
          packetType: packetType,
          status: "InTransit",
          sourceNode: sourceId,
          targetNode: targetId,
          payload: "Sample payload data",
          size: 1500,
          encrypted: newPacket_encrypted,
          timestamp: newPacket_timestamp,
          progress: 0.0,
          position: newPacket_position
        };
        let nextPackets = Belt_Array.concat(state.packets, [newPacket]);
        let match = keepLastN(nextPackets, 2000);
        let droppedForCap = match[1];
        let nextEvents = droppedForCap > 0 ? Belt_Array.concat(state.events, [
            {
              TAG: "PacketSent",
              _0: sourceId,
              _1: targetId,
              _2: packetType
            },
            {
              TAG: "CapacityDrop",
              _0: droppedForCap
            }
          ]) : Belt_Array.concat(state.events, [{
              TAG: "PacketSent",
              _0: sourceId,
              _1: targetId,
              _2: packetType
            }]);
        let match$1 = keepLastN(nextEvents, 1000);
        return {
          nodes: state.nodes,
          packets: match[0],
          events: match$1[0],
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent + 1 | 0,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped + droppedForCap | 0,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "UpdatePacketPositions" :
        let deltaTime = msg._0;
        let match$2 = state.speed;
        let speedMultiplier;
        switch (match$2) {
          case "Paused" :
            speedMultiplier = 0.0;
            break;
          case "Slow" :
            speedMultiplier = 0.5;
            break;
          case "Normal" :
            speedMultiplier = 1.0;
            break;
          case "Fast" :
            speedMultiplier = 2.0;
            break;
          case "VeryFast" :
            speedMultiplier = 4.0;
            break;
        }
        let step = deltaTime * speedMultiplier * 0.001;
        let nodesById = {};
        Belt_Array.forEach(state.nodes, node => {
          nodesById[node.id] = node;
        });
        let updatedPackets = stepPacketsKernel(state.packets, nodesById, step);
        let filteredPackets = Belt_Array.keep(updatedPackets, p => {
          if (p.status !== "Delivered") {
            return true;
          } else {
            return p.progress < 1.2;
          }
        });
        let match$3 = keepLastN(filteredPackets, 2000);
        let droppedForCap$1 = match$3[1];
        let nextEvents$1 = droppedForCap$1 > 0 ? Belt_Array.concat(state.events, [{
              TAG: "CapacityDrop",
              _0: droppedForCap$1
            }]) : state.events;
        let match$4 = keepLastN(nextEvents$1, 1000);
        return {
          nodes: state.nodes,
          packets: match$3[0],
          events: match$4[0],
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime + deltaTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped + droppedForCap$1 | 0,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "PacketArrived" :
        let packetId$1 = msg._0;
        let updatedPackets$1 = Belt_Array.map(state.packets, packet => {
          if (packet.id === packetId$1) {
            return {
              id: packet.id,
              packetType: packet.packetType,
              status: "Delivered",
              sourceNode: packet.sourceNode,
              targetNode: packet.targetNode,
              payload: packet.payload,
              size: packet.size,
              encrypted: packet.encrypted,
              timestamp: packet.timestamp,
              progress: packet.progress,
              position: packet.position
            };
          } else {
            return packet;
          }
        });
        return {
          nodes: state.nodes,
          packets: updatedPackets$1,
          events: state.events,
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered + 1 | 0,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "DropPacket" :
        let packetId$2 = msg._0;
        let updatedPackets$2 = Belt_Array.map(state.packets, packet => {
          if (packet.id === packetId$2) {
            return {
              id: packet.id,
              packetType: packet.packetType,
              status: "Dropped",
              sourceNode: packet.sourceNode,
              targetNode: packet.targetNode,
              payload: packet.payload,
              size: packet.size,
              encrypted: packet.encrypted,
              timestamp: packet.timestamp,
              progress: packet.progress,
              position: packet.position
            };
          } else {
            return packet;
          }
        });
        let nextEvents$2 = Belt_Array.concat(state.events, [{
            TAG: "PacketDropped",
            _0: packetId$2,
            _1: msg._1
          }]);
        let match$5 = keepLastN(nextEvents$2, 1000);
        return {
          nodes: state.nodes,
          packets: updatedPackets$2,
          events: match$5[0],
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped + 1 | 0,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: state.selectedPacket,
          showEventLog: state.showEventLog
        };
      case "SelectPacket" :
        return {
          nodes: state.nodes,
          packets: state.packets,
          events: state.events,
          isRunning: state.isRunning,
          speed: state.speed,
          mode: state.mode,
          currentTime: state.currentTime,
          totalPacketsSent: state.totalPacketsSent,
          totalPacketsDelivered: state.totalPacketsDelivered,
          totalPacketsDropped: state.totalPacketsDropped,
          avgLatency: state.avgLatency,
          showStats: state.showStats,
          selectedPacket: msg._0,
          showEventLog: state.showEventLog
        };
    }
  }
}

function packetTypeColor(packetType) {
  switch (packetType) {
    case "HTTP" :
      return "#4a9eff";
    case "HTTPS" :
      return "#4caf50";
    case "TCP" :
      return "#9c27b0";
    case "UDP" :
      return "#ff9800";
    case "ICMP" :
      return "#f44336";
    case "DNS" :
      return "#00bcd4";
  }
}

function packetTypeLabel(packetType) {
  switch (packetType) {
    case "HTTP" :
      return "HTTP";
    case "HTTPS" :
      return "HTTPS";
    case "TCP" :
      return "TCP";
    case "UDP" :
      return "UDP";
    case "ICMP" :
      return "ICMP";
    case "DNS" :
      return "DNS";
  }
}

function statusColor(status) {
  switch (status) {
    case "InTransit" :
      return "#4a9eff";
    case "Delivered" :
      return "#4caf50";
    case "Dropped" :
      return "#f44336";
    case "Blocked" :
      return "#ff9800";
  }
}

function speedLabel(speed) {
  switch (speed) {
    case "Paused" :
      return "Paused";
    case "Slow" :
      return "0.5x";
    case "Normal" :
      return "1.0x";
    case "Fast" :
      return "2.0x";
    case "VeryFast" :
      return "4.0x";
  }
}

function viewNode(node) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "🖥️",
        style: {
          fontSize: "24px",
          marginBottom: "4px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: node.name,
        style: {
          color: "#e0e6ed",
          fontSize: "11px",
          fontWeight: "600",
          lineHeight: "1.2",
          textAlign: "center"
        }
      })
    ],
    style: {
      background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: "2px solid #4a9eff",
      display: "flex",
      height: "80px",
      left: String(node.x - 50.0) + "px",
      padding: "8px",
      position: "absolute",
      top: String(node.y - 40.0) + "px",
      width: "100px",
      zIndex: "10",
      borderRadius: "12px",
      alignItems: "center",
      flexDirection: "column",
      justifyContent: "center"
    }
  }, node.id);
}

function viewPacket(packet, dispatch) {
  let match = packet.position;
  let match$1 = packet.status;
  let tmp;
  switch (match$1) {
    case "InTransit" :
      tmp = "1.0";
      break;
    case "Delivered" :
      tmp = "0.3";
      break;
    case "Dropped" :
    case "Blocked" :
      tmp = "0.5";
      break;
  }
  return JsxRuntime.jsx("div", {
    children: packet.encrypted ? "🔒" : "📦",
    style: {
      background: packetTypeColor(packet.packetType),
      border: "2px solid white",
      cursor: "pointer",
      display: "flex",
      fontSize: "14px",
      height: "30px",
      left: String(match[0] - 15.0) + "px",
      position: "absolute",
      top: String(match[1] - 15.0) + "px",
      width: "30px",
      zIndex: "20",
      opacity: tmp,
      borderRadius: "50%",
      boxShadow: "0 0 10px " + packetTypeColor(packet.packetType),
      alignItems: "center",
      justifyContent: "center",
      transition: "all 0.1s"
    },
    onClick: param => dispatch({
      TAG: "SelectPacket",
      _0: packet.id
    })
  }, packet.id);
}

function viewEvent(event, index) {
  let match;
  switch (event.TAG) {
    case "PacketSent" :
      match = [
        "📤",
        "#4a9eff",
        `Packet sent: ` + event._0 + ` → ` + event._1 + ` (` + packetTypeLabel(event._2) + `)`
      ];
      break;
    case "PacketReceived" :
      match = [
        "📥",
        "#4caf50",
        `Packet received: ` + event._0
      ];
      break;
    case "PacketDropped" :
      match = [
        "❌",
        "#f44336",
        `Packet dropped: ` + event._0 + ` - ` + event._1
      ];
      break;
    case "CapacityDrop" :
      match = [
        "🛑",
        "#ff9800",
        `Backpressure: dropped ` + String(event._0) + ` packet(s) to stay under cap`
      ];
      break;
    case "ConnectionEstablished" :
      match = [
        "🔗",
        "#4caf50",
        `Connection: ` + event._0 + ` ↔ ` + event._1
      ];
      break;
    case "ConnectionClosed" :
      match = [
        "🔌",
        "#9e9e9e",
        `Disconnected: ` + event._0 + ` ↔ ` + event._1
      ];
      break;
    case "FirewallBlock" :
      match = [
        "🚫",
        "#ff9800",
        `Firewall blocked: ` + event._0 + ` → ` + event._1 + `:` + String(event._2)
      ];
      break;
    case "LatencySpike" :
      match = [
        "⚠️",
        "#ff9800",
        `Latency spike: ` + event._0 + ` (` + String(event._1) + `ms)`
      ];
      break;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("span", {
        children: match[0],
        style: {
          marginRight: "8px"
        }
      }),
      match[2]
    ],
    style: {
      background: "rgba(255, 255, 255, 0.05)",
      borderLeft: "3px solid " + match[1],
      color: "#b0b8c4",
      fontFamily: "monospace",
      fontSize: "12px",
      marginBottom: "4px",
      padding: "8px 12px"
    }
  }, String(index));
}

function SimulationMode(props) {
  let onStateChange = props.onStateChange;
  let initialState = props.initialState;
  let match = React.useState(() => {
    if (initialState !== undefined) {
      return initialState;
    } else {
      return init;
    }
  });
  let setState = match[1];
  let state = match[0];
  let dispatch = msg => {
    let newState = update(msg, state);
    setState(param => newState);
    if (onStateChange !== undefined) {
      return onStateChange(newState);
    }
  };
  React.useEffect(() => {
    if (!state.isRunning) {
      return;
    }
    let animationId = 0;
    Date.now();
    animationId = (requestAnimationFrame(animate));
    return () => ((cancelAnimationFrame(animationId.contents)));
  }, [state.isRunning]);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "🎮 Simulation Mode",
            style: {
              background: "linear-gradient(135deg, #4a9eff, #00bcd4)",
              fontSize: "32px",
              fontWeight: "700",
              marginBottom: "8px"
            }
          }),
          JsxRuntime.jsx("p", {
            children: "Cisco Packet Tracer-style network simulation",
            style: {
              color: "#8892a6",
              fontSize: "16px"
            }
          })
        ],
        style: {
          marginBottom: "24px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              state.isRunning ? JsxRuntime.jsx("button", {
                  children: "⏸️ Pause",
                  style: {
                    background: "linear-gradient(135deg, #ff9800, #ffb74d)",
                    border: "none",
                    color: "white",
                    cursor: "pointer",
                    fontSize: "14px",
                    fontWeight: "600",
                    padding: "10px 20px",
                    borderRadius: "8px"
                  },
                  onClick: param => dispatch("PauseSimulation")
                }) : JsxRuntime.jsx("button", {
                  children: "▶️ Start",
                  style: {
                    background: "linear-gradient(135deg, #4caf50, #66bb6a)",
                    border: "none",
                    color: "white",
                    cursor: "pointer",
                    fontSize: "14px",
                    fontWeight: "600",
                    padding: "10px 20px",
                    borderRadius: "8px"
                  },
                  onClick: param => dispatch("StartSimulation")
                }),
              JsxRuntime.jsx("button", {
                children: "⏹️ Stop",
                style: {
                  background: "linear-gradient(135deg, #f44336, #e57373)",
                  border: "none",
                  color: "white",
                  cursor: "pointer",
                  fontSize: "14px",
                  fontWeight: "600",
                  padding: "10px 20px",
                  borderRadius: "8px"
                },
                onClick: param => dispatch("StopSimulation")
              })
            ],
            style: {
              display: "flex",
              gap: "8px"
            }
          }),
          JsxRuntime.jsx("div", {
            children: Belt_Array.map([
              "Slow",
              "Normal",
              "Fast",
              "VeryFast"
            ], speed => JsxRuntime.jsx("button", {
              children: speedLabel(speed),
              style: {
                background: state.speed === speed ? "#4a9eff" : "#2a3142",
                border: "none",
                color: "white",
                cursor: "pointer",
                fontSize: "13px",
                fontWeight: "600",
                padding: "8px 16px",
                borderRadius: "6px"
              },
              onClick: param => dispatch({
                TAG: "SetSpeed",
                _0: speed
              })
            }, speedLabel(speed))),
            style: {
              display: "flex",
              gap: "8px"
            }
          }),
          JsxRuntime.jsx("button", {
            children: "📤 Send Test Packet",
            style: {
              background: "linear-gradient(135deg, #4a9eff, #7b6cff)",
              border: "none",
              color: "white",
              cursor: "pointer",
              fontSize: "14px",
              fontWeight: "600",
              padding: "10px 20px",
              borderRadius: "8px"
            },
            onClick: param => dispatch({
              TAG: "SendPacket",
              _0: "node-1",
              _1: "node-3",
              _2: "HTTPS"
            })
          })
        ],
        style: {
          background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
          border: "2px solid #2a3142",
          display: "flex",
          marginBottom: "24px",
          padding: "16px",
          borderRadius: "12px",
          gap: "16px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              Belt_Array.map(state.nodes, viewNode),
              Belt_Array.map(state.packets, packet => viewPacket(packet, dispatch)),
              JsxRuntime.jsxs("svg", {
                children: [
                  JsxRuntime.jsx("line", {
                    stroke: "#2a3142",
                    strokeDasharray: "5,5",
                    strokeWidth: "2",
                    x1: "150",
                    x2: "450",
                    y1: "250",
                    y2: "250"
                  }),
                  JsxRuntime.jsx("line", {
                    stroke: "#2a3142",
                    strokeDasharray: "5,5",
                    strokeWidth: "2",
                    x1: "450",
                    x2: "750",
                    y1: "250",
                    y2: "250"
                  })
                ],
                style: {
                  height: "100%",
                  left: "0",
                  position: "absolute",
                  top: "0",
                  width: "100%",
                  zIndex: "5",
                  pointerEvents: "none"
                }
              })
            ],
            style: {
              background: "linear-gradient(135deg, #0a0e1a 0%, #1e2431 100%)",
              border: "2px solid #2a3142",
              height: "600px",
              overflow: "hidden",
              position: "relative",
              borderRadius: "16px",
              flex: "1"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              state.showStats ? JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("h3", {
                      children: "📊 Statistics",
                      style: {
                        color: "#e0e6ed",
                        fontSize: "16px",
                        fontWeight: "700",
                        marginBottom: "16px"
                      }
                    }),
                    JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                              children: String(state.totalPacketsSent),
                              style: {
                                color: "#4a9eff",
                                fontSize: "24px",
                                fontWeight: "700"
                              }
                            }),
                            JsxRuntime.jsx("div", {
                              children: "Packets Sent",
                              style: {
                                color: "#8892a6",
                                fontSize: "12px"
                              }
                            })
                          ]
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                              children: String(state.totalPacketsDelivered),
                              style: {
                                color: "#4caf50",
                                fontSize: "24px",
                                fontWeight: "700"
                              }
                            }),
                            JsxRuntime.jsx("div", {
                              children: "Delivered",
                              style: {
                                color: "#8892a6",
                                fontSize: "12px"
                              }
                            })
                          ]
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                              children: String(state.totalPacketsDropped),
                              style: {
                                color: "#f44336",
                                fontSize: "24px",
                                fontWeight: "700"
                              }
                            }),
                            JsxRuntime.jsx("div", {
                              children: "Dropped",
                              style: {
                                color: "#8892a6",
                                fontSize: "12px"
                              }
                            })
                          ]
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                              children: String(state.packets.length),
                              style: {
                                color: "#ff9800",
                                fontSize: "24px",
                                fontWeight: "700"
                              }
                            }),
                            JsxRuntime.jsx("div", {
                              children: "In Transit",
                              style: {
                                color: "#8892a6",
                                fontSize: "12px"
                              }
                            })
                          ]
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                              children: String(2000),
                              style: {
                                color: "#8892a6",
                                fontSize: "20px",
                                fontWeight: "700"
                              }
                            }),
                            JsxRuntime.jsx("div", {
                              children: "Packet Cap",
                              style: {
                                color: "#8892a6",
                                fontSize: "12px"
                              }
                            })
                          ]
                        }),
                        JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                              children: PacketMathWasm.isWasmActive() && PacketMathWasm.isAddWasmActive() ? "WASM" : "JS",
                              style: {
                                color: "#00bcd4",
                                fontSize: "20px",
                                fontWeight: "700"
                              }
                            }),
                            JsxRuntime.jsx("div", {
                              children: "Packet Kernel",
                              style: {
                                color: "#8892a6",
                                fontSize: "12px"
                              }
                            })
                          ]
                        })
                      ],
                      style: {
                        display: "flex",
                        flexDirection: "column",
                        gap: "12px"
                      }
                    })
                  ],
                  style: {
                    background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
                    border: "2px solid #2a3142",
                    padding: "20px",
                    borderRadius: "12px"
                  }
                }) : null,
              state.showEventLog ? JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                          children: "📋 Event Log",
                          style: {
                            color: "#e0e6ed",
                            fontSize: "16px",
                            fontWeight: "700"
                          }
                        }),
                        JsxRuntime.jsx("button", {
                          children: "Clear",
                          style: {
                            background: "#2a3142",
                            border: "none",
                            color: "#8892a6",
                            cursor: "pointer",
                            fontSize: "11px",
                            padding: "4px 12px",
                            borderRadius: "4px"
                          },
                          onClick: param => dispatch("ClearEvents")
                        })
                      ],
                      style: {
                        display: "flex",
                        marginBottom: "12px",
                        justifyContent: "space-between"
                      }
                    }),
                    state.events.length !== 0 ? Belt_Array.mapWithIndex(state.events, (index, event) => viewEvent(event, index)) : JsxRuntime.jsx("div", {
                        children: "No events yet",
                        style: {
                          color: "#8892a6",
                          fontSize: "12px",
                          padding: "20px",
                          textAlign: "center"
                        }
                      })
                  ],
                  style: {
                    background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
                    border: "2px solid #2a3142",
                    maxHeight: "400px",
                    overflow: "auto",
                    padding: "20px",
                    borderRadius: "12px",
                    flex: "1"
                  }
                }) : null
            ],
            style: {
              display: "flex",
              width: "300px",
              flexDirection: "column",
              gap: "16px"
            }
          })
        ],
        style: {
          display: "flex",
          gap: "24px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("strong", {
            children: "💡 Simulation Tips: ",
            style: {
              color: "#4a9eff",
              fontSize: "13px"
            }
          }),
          JsxRuntime.jsx("span", {
            children: "Click packets for details. Adjust speed to observe traffic patterns. Use test packets to verify connectivity.",
            style: {
              color: "#b0b8c4",
              fontSize: "13px"
            }
          })
        ],
        style: {
          background: "rgba(74, 158, 255, 0.1)",
          border: "2px solid #4a9eff",
          marginTop: "24px",
          padding: "16px",
          borderRadius: "12px"
        }
      })
    ],
    className: "simulation-mode",
    style: {
      background: "#0a0e1a",
      minHeight: "100vh",
      padding: "32px"
    }
  });
}

let maxActivePackets = 2000;

let maxEventLogEntries = 1000;

let make = SimulationMode;

export {
  maxActivePackets,
  maxEventLogEntries,
  keepLastN,
  enforcePacketCap,
  enforceEventCap,
  stepPacketsKernel,
  init,
  update,
  packetTypeColor,
  packetTypeLabel,
  statusColor,
  speedLabel,
  viewNode,
  viewPacket,
  viewEvent,
  make,
}
/* react Not a pure module */
