// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function nextRef(conn) {
  conn.ref = conn.ref + 1 | 0;
  return String(conn.ref);
}

function encodeMsg(joinRef, ref, topic, event, payload) {
  let jr = joinRef !== undefined ? joinRef : null;
  return JSON.stringify([
    jr,
    ref,
    topic,
    event,
    payload
  ]);
}

function decodeMsg(raw) {
  let json;
  try {
    json = JSON.parse(raw);
  } catch (exn) {
    return;
  }
  if (!Array.isArray(json)) {
    return;
  }
  if (json.length < 5) {
    return;
  }
  let s = Belt_Option.getWithDefault(Belt_Array.get(json, 0), null);
  let jr;
  jr = typeof s === "string" ? s : undefined;
  let s$1 = Belt_Option.getWithDefault(Belt_Array.get(json, 1), null);
  let r;
  r = typeof s$1 === "string" ? s$1 : undefined;
  let s$2 = Belt_Option.getWithDefault(Belt_Array.get(json, 2), null);
  let topic;
  topic = typeof s$2 === "string" ? s$2 : "";
  let s$3 = Belt_Option.getWithDefault(Belt_Array.get(json, 3), null);
  let event;
  event = typeof s$3 === "string" ? s$3 : "";
  let payload = Belt_Option.getWithDefault(Belt_Array.get(json, 4), null);
  return {
    joinRef: jr,
    ref: r,
    topic: topic,
    event: event,
    payload: payload
  };
}

function findChannel(conn, topic) {
  return Belt_Array.getBy(conn.channels, ch => ch.topic === topic);
}

function make() {
  return {
    ws: undefined,
    state: "Disconnected",
    ref: 0,
    channels: [],
    heartbeatTimer: undefined,
    onStateChange: undefined
  };
}

function onStateChange(conn, cb) {
  conn.onStateChange = cb;
}

function notifyState(conn) {
  let cb = conn.onStateChange;
  if (cb !== undefined) {
    return cb(conn.state);
  }
}

function connect(conn, url) {
  conn.state = "Connecting";
  notifyState(conn);
  let ws = new WebSocket(url);
  conn.ws = Primitive_option.some(ws);
  ws.onopen = () => {
    conn.state = "Connected";
    notifyState(conn);
    console.log("[Socket] Connected to " + url);
    let timer = setInterval(() => {
      if (ws.readyState !== 1) {
        return;
      }
      let ref = nextRef(conn);
      let msg = encodeMsg(undefined, ref, "phoenix", "heartbeat", {});
      ws.send(msg);
    }, 30000);
    conn.heartbeatTimer = Primitive_option.some(timer);
    Belt_Array.forEach(conn.channels, ch => {
      let ref = nextRef(conn);
      ch.joinRef = ref;
      ch.state = "Joining";
      let msg = encodeMsg(ref, ref, ch.topic, "phx_join", {});
      ws.send(msg);
    });
  };
  ws.onclose = _event => {
    conn.state = "Disconnected";
    conn.ws = undefined;
    notifyState(conn);
    console.log("[Socket] Disconnected");
    let timer = conn.heartbeatTimer;
    if (timer !== undefined) {
      clearInterval(Primitive_option.valFromOption(timer));
      conn.heartbeatTimer = undefined;
      return;
    }
  };
  ws.onerror = _event => {
    conn.state = "Errored";
    notifyState(conn);
    console.error("[Socket] Connection error");
  };
  ws.onmessage = event => {
    let msg = decodeMsg(event.data);
    if (msg !== undefined) {
      if (msg.event === "phx_reply") {
        let ch = findChannel(conn, msg.topic);
        if (ch !== undefined && ch.state === "Joining") {
          ch.state = "Joined";
          console.log("[Socket] Joined " + msg.topic);
          return;
        } else {
          return;
        }
      }
      let ch$1 = findChannel(conn, msg.topic);
      if (ch$1 === undefined) {
        return;
      }
      let callbacks = ch$1.handlers[msg.event];
      if (callbacks !== undefined) {
        return Belt_Array.forEach(callbacks, cb => cb(msg.payload));
      } else {
        return;
      }
    }
    console.warn("[Socket] Failed to decode message");
  };
}

function disconnect(conn) {
  let ws = conn.ws;
  if (ws !== undefined) {
    Primitive_option.valFromOption(ws).close();
  }
  conn.ws = undefined;
  conn.state = "Disconnected";
  notifyState(conn);
  let timer = conn.heartbeatTimer;
  if (timer !== undefined) {
    clearInterval(Primitive_option.valFromOption(timer));
    conn.heartbeatTimer = undefined;
    return;
  }
}

function channel(conn, topic) {
  let ch = {
    topic: topic,
    state: "Left",
    joinRef: "0",
    handlers: {}
  };
  conn.channels = Belt_Array.concat(conn.channels, [ch]);
  return ch;
}

function joinChannel(conn, ch) {
  let ws = conn.ws;
  if (ws === undefined) {
    ch.state = "Joining";
    return;
  }
  let ws$1 = Primitive_option.valFromOption(ws);
  if (ws$1.readyState !== 1) {
    ch.state = "Joining";
    return;
  }
  let ref = nextRef(conn);
  ch.joinRef = ref;
  ch.state = "Joining";
  let msg = encodeMsg(ref, ref, ch.topic, "phx_join", {});
  ws$1.send(msg);
}

function leaveChannel(conn, ch) {
  let ws = conn.ws;
  if (ws !== undefined) {
    let ws$1 = Primitive_option.valFromOption(ws);
    if (ws$1.readyState === 1) {
      let ref = nextRef(conn);
      let msg = encodeMsg(ch.joinRef, ref, ch.topic, "phx_leave", {});
      ws$1.send(msg);
    }
  }
  ch.state = "Left";
}

function on(ch, event, callback) {
  let arr = ch.handlers[event];
  let existing = arr !== undefined ? arr : [];
  ch.handlers[event] = Belt_Array.concat(existing, [callback]);
}

function push(conn, ch, event, payload) {
  let ws = conn.ws;
  if (ws !== undefined) {
    let ws$1 = Primitive_option.valFromOption(ws);
    if (ws$1.readyState === 1 && ch.state === "Joined") {
      let ref = nextRef(conn);
      let msg = encodeMsg(ch.joinRef, ref, ch.topic, event, payload);
      ws$1.send(msg);
      return;
    }
    console.warn("[Socket] Cannot push — not connected or channel not joined");
    return;
  }
  console.warn("[Socket] Cannot push — not connected or channel not joined");
}

function defaultUrl() {
  let proto = window["location.protocol"] === "https:" ? "wss://" : "ws://";
  return proto + window["location.host"] + "/socket/websocket";
}

let wsConnecting = 0;

let wsOpen = 1;

let _wsClosed = 3;

export {
  wsConnecting,
  wsOpen,
  _wsClosed,
  nextRef,
  encodeMsg,
  decodeMsg,
  findChannel,
  make,
  onStateChange,
  notifyState,
  connect,
  disconnect,
  channel,
  joinChannel,
  leaveChannel,
  on,
  push,
  defaultUrl,
}
/* No side effect */
