// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function toCiscoComponent(comp) {
  let match = comp.componentType;
  let shape;
  switch (match) {
    case "CerroTorre" :
    case "Svalinn" :
      shape = "Gateway";
      break;
    case "Volume" :
      shape = "Oval";
      break;
    default:
      shape = "Box";
  }
  return {
    id: comp.id,
    shape: shape,
    label: Model.componentTypeToString(comp.componentType),
    position: comp.position,
    size: [
      150.0,
      100.0
    ],
    ports: [],
    config: comp.config,
    children: []
  };
}

function renderShape(comp, isSelected, isDark) {
  let match = comp.size;
  let height = match[1];
  let width = match[0];
  let x = comp.position.x;
  let y = comp.position.y;
  let borderColor = isDark ? "#CCCCCC" : "#333333";
  let fillColor = isDark ? "#1A1A1A" : "#F5F5F5";
  let selectedBorder = isDark ? "#66B2FF" : "#0052CC";
  let strokeWidth = isSelected ? "3" : "2";
  let stroke = isSelected ? selectedBorder : borderColor;
  let match$1 = comp.shape;
  switch (match$1) {
    case "Box" :
      return JsxRuntime.jsx("rect", {
        "aria-label": comp.label + " container (box shape)",
        role: "graphics-symbol",
        height: String(height),
        width: String(width),
        fill: fillColor,
        rx: "8",
        stroke: stroke,
        strokeWidth: strokeWidth,
        x: String(x),
        y: String(y)
      });
    case "Oval" :
      return JsxRuntime.jsx("ellipse", {
        "aria-label": comp.label + " container (oval shape)",
        role: "graphics-symbol",
        cx: String(x + width / 2.0),
        cy: String(y + height / 2.0),
        fill: fillColor,
        rx: String(width / 2.0),
        ry: String(height / 2.0),
        stroke: stroke,
        strokeWidth: strokeWidth
      });
    case "Gateway" :
      return JsxRuntime.jsx("rect", {
        "aria-label": comp.label + " security gateway",
        role: "graphics-symbol",
        height: String(height),
        width: String(width),
        fill: fillColor,
        rx: "8",
        stroke: stroke,
        strokeDasharray: "10,5",
        strokeWidth: "4",
        x: String(x),
        y: String(y)
      });
    case "Nested" :
      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsx("rect", {
            "aria-label": comp.label + " nested container group",
            role: "graphics-symbol",
            height: String(height),
            width: String(width),
            fill: fillColor,
            rx: "8",
            stroke: stroke,
            strokeWidth: strokeWidth,
            x: String(x),
            y: String(y)
          }),
          Belt_Array.mapWithIndex(comp.children, (idx, child) => {
            let childX = x + 20.0 + idx * 30.0;
            let childY = y + 40.0;
            return renderShape({
              id: child.id,
              shape: child.shape,
              label: child.label,
              position: {
                x: childX,
                y: childY
              },
              size: child.size,
              ports: child.ports,
              config: child.config,
              children: child.children
            }, false, isDark);
          })
        ]
      });
  }
}

function renderConnection(conn, components, isDark) {
  let fromComp = Belt_Array.getBy(components, c => c.id === conn.from);
  let toComp = Belt_Array.getBy(components, c => c.id === conn.to);
  if (fromComp === undefined) {
    return null;
  }
  if (toComp === undefined) {
    return null;
  }
  let x1 = fromComp.position.x + 75.0;
  let y1 = fromComp.position.y + 50.0;
  let x2 = toComp.position.x + 75.0;
  let y2 = toComp.position.y + 50.0;
  let midX = (x1 + x2) / 2.0;
  let path = `M ` + String(x1) + ` ` + String(y1) + ` Q ` + String(midX) + ` ` + String(y1) + ` ` + String(midX) + ` ` + String((y1 + y2) / 2.0) + ` T ` + String(x2) + ` ` + String(y2);
  return JsxRuntime.jsx("path", {
    "aria-label": "Connection from component to component",
    role: "graphics-symbol",
    d: path,
    fill: "none",
    markerEnd: "url(#arrowhead)",
    stroke: isDark ? "#66B2FF" : "#0052CC",
    strokeWidth: "2"
  });
}

function renderConfigPanel(component, isDark, dispatch) {
  if (component !== undefined) {
    return JsxRuntime.jsxs("aside", {
      children: [
        JsxRuntime.jsx("h3", {
          children: Model.componentTypeToString(component.componentType),
          style: {
            fontSize: "1.2rem",
            marginBottom: "1rem"
          }
        }),
        JsxRuntime.jsxs("form", {
          children: [
            JsxRuntime.jsxs("fieldset", {
              children: [
                JsxRuntime.jsx("legend", {
                  children: "Shape",
                  style: {
                    fontWeight: "600",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    JsxRuntime.jsx("input", {
                      defaultChecked: true,
                      name: "shape",
                      type: "radio",
                      value: "box"
                    }),
                    " Box"
                  ],
                  style: {
                    display: "block",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    JsxRuntime.jsx("input", {
                      name: "shape",
                      type: "radio",
                      value: "oval"
                    }),
                    " Oval"
                  ],
                  style: {
                    display: "block",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    JsxRuntime.jsx("input", {
                      name: "shape",
                      type: "radio",
                      value: "gateway"
                    }),
                    " Gateway"
                  ],
                  style: {
                    display: "block"
                  }
                })
              ],
              style: {
                border: "none",
                marginBottom: "1rem",
                padding: "0"
              }
            }),
            JsxRuntime.jsxs("fieldset", {
              children: [
                JsxRuntime.jsx("legend", {
                  children: "Ports",
                  style: {
                    fontWeight: "600",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsx("input", {
                  "aria-label": "Port mapping",
                  style: {
                    backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                    border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                    borderRadius: "4px",
                    color: isDark ? "#FFFFFF" : "#000000",
                    padding: "0.5rem",
                    width: "100%"
                  },
                  placeholder: "8080:80",
                  type: "text"
                })
              ],
              style: {
                border: "none",
                marginBottom: "1rem",
                padding: "0"
              }
            }),
            JsxRuntime.jsxs("fieldset", {
              children: [
                JsxRuntime.jsx("legend", {
                  children: "Resources",
                  style: {
                    fontWeight: "600",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    "CPU (cores)",
                    JsxRuntime.jsx("input", {
                      "aria-label": "CPU cores",
                      defaultValue: "1.0",
                      style: {
                        backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                        border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                        color: isDark ? "#FFFFFF" : "#000000",
                        marginTop: "0.25rem",
                        padding: "0.5rem",
                        width: "100%",
                        borderRadius: "4px"
                      },
                      min: "0.1",
                      step: 0.1,
                      type: "number"
                    })
                  ],
                  style: {
                    display: "block",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    "Memory (MB)",
                    JsxRuntime.jsx("input", {
                      "aria-label": "Memory in megabytes",
                      defaultValue: "512",
                      style: {
                        backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                        border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                        color: isDark ? "#FFFFFF" : "#000000",
                        marginTop: "0.25rem",
                        padding: "0.5rem",
                        width: "100%",
                        borderRadius: "4px"
                      },
                      min: "128",
                      step: 128.0,
                      type: "number"
                    })
                  ],
                  style: {
                    display: "block"
                  }
                })
              ],
              style: {
                border: "none",
                marginBottom: "1rem",
                padding: "0"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                  children: "Apply",
                  "aria-label": "Apply configuration changes",
                  style: {
                    backgroundColor: isDark ? "#66B2FF" : "#0052CC",
                    border: "none",
                    color: "white",
                    cursor: "pointer",
                    fontWeight: "600",
                    padding: "0.75rem",
                    borderRadius: "6px",
                    flex: "1"
                  },
                  type: "submit"
                }),
                JsxRuntime.jsx("button", {
                  children: "Cancel",
                  "aria-label": "Cancel configuration",
                  style: {
                    backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                    border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                    color: isDark ? "#FFFFFF" : "#000000",
                    cursor: "pointer",
                    fontWeight: "600",
                    padding: "0.75rem",
                    borderRadius: "6px",
                    flex: "1"
                  },
                  type: "button",
                  onClick: param => dispatch({
                    TAG: "SelectComponent",
                    _0: undefined
                  })
                })
              ],
              style: {
                display: "flex",
                marginTop: "1rem",
                gap: "0.5rem"
              }
            })
          ],
          onSubmit: e => {
            e.preventDefault();
          }
        })
      ],
      "aria-label": "Configuration for " + Model.componentTypeToString(component.componentType),
      role: "complementary",
      style: {
        backgroundColor: isDark ? "#000000" : "#FFFFFF",
        borderLeft: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
        color: isDark ? "#FFFFFF" : "#000000",
        padding: "1.5rem",
        width: "300px"
      }
    });
  } else {
    return JsxRuntime.jsxs("aside", {
      children: [
        JsxRuntime.jsx("h3", {
          children: "Configuration",
          style: {
            fontSize: "1.2rem",
            marginBottom: "1rem"
          }
        }),
        JsxRuntime.jsx("p", {
          children: "Click a component to configure it",
          style: {
            opacity: "0.7"
          }
        })
      ],
      "aria-label": "Configuration panel",
      role: "complementary",
      style: {
        backgroundColor: isDark ? "#000000" : "#FFFFFF",
        borderLeft: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
        color: isDark ? "#FFFFFF" : "#000000",
        padding: "1.5rem",
        width: "300px"
      }
    });
  }
}

function view(model, isDark, dispatch) {
  let ciscoComponents = Belt_Array.map(model.components, toCiscoComponent);
  let id = model.selectedComponent;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("svg", {
        children: [
          JsxRuntime.jsx("defs", {
            children: JsxRuntime.jsx("marker", {
              children: JsxRuntime.jsx("polygon", {
                fill: isDark ? "#66B2FF" : "#0052CC",
                points: "0 0, 10 3, 0 6"
              }),
              id: "arrowhead",
              markerHeight: "10",
              markerWidth: "10",
              orient: "auto",
              refX: "9",
              refY: "3"
            })
          }),
          JsxRuntime.jsxs("pattern", {
            children: [
              JsxRuntime.jsx("rect", {
                height: "20",
                width: "20",
                fill: "transparent"
              }),
              JsxRuntime.jsx("path", {
                d: "M 20 0 L 0 0 0 20",
                fill: "none",
                stroke: isDark ? "#1A1A1A" : "#E0E0E0",
                strokeWidth: "0.5"
              })
            ],
            id: "grid",
            height: "20",
            width: "20",
            patternUnits: "userSpaceOnUse"
          }),
          JsxRuntime.jsx("rect", {
            height: "100%",
            width: "100%",
            fill: "url(#grid)"
          }),
          Belt_Array.map(model.connections, conn => renderConnection(conn, model.components, isDark)),
          Belt_Array.map(ciscoComponents, comp => {
            let id = model.selectedComponent;
            let isSelected = id !== undefined ? id === comp.id : false;
            return JsxRuntime.jsxs("g", {
              children: [
                renderShape(comp, isSelected, isDark),
                JsxRuntime.jsx("text", {
                  children: comp.label,
                  style: {
                    fontSize: "14px",
                    fontWeight: "600",
                    pointerEvents: "none"
                  },
                  dominantBaseline: "middle",
                  fill: isDark ? "#FFFFFF" : "#000000",
                  textAnchor: "middle",
                  x: String(comp.position.x + comp.size[0] / 2.0),
                  y: String(comp.position.y + comp.size[1] / 2.0)
                })
              ],
              style: {
                cursor: "pointer"
              },
              onClick: param => dispatch({
                TAG: "SelectComponent",
                _0: comp.id
              })
            }, comp.id);
          })
        ],
        "aria-label": "Container network topology",
        role: "graphics-document",
        height: "100%",
        width: "100%"
      }),
      renderConfigPanel(id !== undefined ? Belt_Array.getBy(model.components, c => c.id === id) : undefined, isDark, dispatch)
    ],
    "aria-label": "Cisco-style network topology designer",
    role: "main",
    style: {
      backgroundColor: isDark ? "#000000" : "#FFFFFF",
      color: isDark ? "#FFFFFF" : "#000000",
      display: "flex",
      height: "100vh"
    }
  });
}

export {
  toCiscoComponent,
  renderShape,
  renderConnection,
  renderConfigPanel,
  view,
}
/* react/jsx-runtime Not a pure module */
