// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DomMounterEnhanced from "./DomMounterEnhanced.res.js";

let VueFFI = {};

function useDomMounterVue(elementId) {
  let mounted = ref(false);
  let error = ref(undefined);
  onMounted(() => {
    let msg = DomMounterEnhanced.mount(elementId);
    if (msg.TAG === "Ok") {
      mounted.value = true;
      return;
    }
    error.value = msg._0;
  });
  onUnmounted(() => {
    mounted.value = false;
    error.value = undefined;
  });
  return {
    mounted: mounted,
    error: error
  };
}

export {
  VueFFI,
  useDomMounterVue,
}
/* No side effect */
